### ISSUE TITLE
VMs: Automatic Windows updates?

### ISSUE THREAD

**Issue by Thorium** [CompositionalIT/farmer#1002]
Are the Windows-updates (and security patches) automatically on or off with deployed VMs?

The ARM template does:
```json
    "osProfile": {
          "adminPassword": "[parameters('password')]",
          "adminUsername": "MyAdmin",
          "computerName": "MyServer"
    },
```

...where the automatic updates goes at `windowsConfiguration`:

```json
  "osProfile": {
        "adminPassword": "[parameters('password')]",
        "adminUsername": "MyAdmin",
        "computerName": "MyServer",
	"windowsConfiguration": {
		"enableAutomaticUpdates": true,
		"patchSettings": {
			"patchMode": "AutomaticByPlatform",
			"assessmentMode": "AutomaticByPlatform"
		}
	}
  },
```

But what is the default setting?
I expect this is not a parameter in Farmer template?

**Comment by isaacabraham** [comment]
Looks like it's already on.

https://learn.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachines?pivots=deployment-language-arm-template#windowsconfiguration-1

**Comment by Thorium** [comment]
This gives you false sense of security.
Here is an actual screen-capture of remote-desktop to a standalone VM created by Farmer script:

![image](https://github.com/CompositionalIT/farmer/assets/229355/5753e3b6-a55a-45db-93ac-e240703d32f3)

What organization? This was a standalone test machine, not an AD computer...
