### ISSUE TITLE
webApp secret_setting for ENV_PARAM with underscores

### ISSUE THREAD

**Issue by l3m** [CompositionalIT/farmer#1035]
I am try to add a environment parameter to a ```webApp``` with a app-given name that I cannot change (e.g. ```MY_USER_NAME```). 

KeyVault doesn't allow me to create secrets with names with underscores, so I am wondering how I can set the environment variable to MY_USER_NAME with a value from the KeyVault. 

Is this possible? If so, how?

**Comment by mike-wade** [comment]
I have the same issue but with `:` to indicate a setting in a section. I suspect `Farmer\Builders\Builders.WebApp.fs:343` will need tweaking so that it forces the setting name to match what keyvault permits.
