### ISSUE TITLE
Add Support to P0V3 service plan

### ISSUE THREAD

**Issue by MarcoGix** [CompositionalIT/farmer#1062]
Hi all,

could you please add support for WEbApp service plan P0V3?

On type SKU
`        | Premium0V3 of string`
`        static member P3V3 = Premium0V3 "P0v3"`

Thanks!

**Comment by martinbryant** [comment]
Hi @MarcoGix - hopefully using the following will achieve what you need

`
let webApp = webApp {
    name "web"
    sku (WebApp.Sku.PremiumV3 "P0v3")
}
`

**Comment by MarcoGix** [comment]
Hi @martinbryant and thanks!

I saw that approach before opening the issue but I found a difference beetwen 
`PremiumV3 ` - `Premium0V3`

So I was thinking they were different and not yet supported.
Deployed worked tahnks!
