### ISSUE TITLE
CosmosDB Gremlin support 

### ISSUE THREAD

**Issue by oco-adam** [CompositionalIT/farmer#1097]
Hi, 

Firstly, thanks very much for this excellent piece of technology!

Secondly, we're new to Farmer and would like to deploy a Gremlin-enabled CosmosDB account. I see in the docs that it currently says "with support for Gremlin, Table and Cassandra data models planned...".

So was just wondering if this is in the pipeline, and if not then do you have any best practice workarounds in the meantime?

**Comment by oco-adam** [comment]
Hi @Larocceau, thanks for your quick response. Yes, if time/deadlines will allow it, then I'd very much like to have a go at implementing this. But if you could possibly give me a couple of pointers as to how I could get started then would be much appreciated.

**Comment by isaacabraham** [comment]
Hi @oco-adam - the best place to start is https://compositionalit.github.io/farmer/contributing/ and https://compositionalit.github.io/farmer/contributing/adding-resources/. These guides give some tips - basically you need to find out how the ARM should look, and then start to modify the F# side of things to emit the appropriate ARM.

If you can even supply some ARM samples, that's 90% of the battle - one of us could probably add the F# side of things without that much effort, or pair with you so you know how to make similar changes in future.
