### ISSUE TITLE
Template violation when using pgserver.FullyQualifiedDomainName in setting

### ISSUE THREAD

**Issue by Janna112358** [CompositionalIT/farmer#1139]
I ran into this using code based on ["webapp pg farmer sample"](https://github.com/CompositionalIT/webapp-pg-farmer-sample/issues/1) so I opened the issue there originally :)

Farmer version: 1.8.13

**Comment by isaacabraham** [comment]
Hey @Janna112358 could you send a slightly more complete sample - I think I have a fix, but ideally would like to do an end-to-end test before releasing a fix.

**Comment by isaacabraham** [comment]
You can also test this yourself:

```fsharp
type PostgreSQLConfig with
    member this.FixedFqdn =
        ArmExpression
            .reference(Farmer.Arm.DBforPostgreSQL.servers.resourceId this.Name)
            .Map(fun r -> r + ".fullyQualifiedDomainName")
            .Eval()
```

If you can confirm that this works, I'm happy to push it directly without an end-to-end test myself.

**Comment by isaacabraham** [comment]
Ok on further inspection there were a few issues left from the move to flexible servers that I've now fixed.
