### ISSUE TITLE
Create resource to existing resource group

### ISSUE THREAD

**Issue by clement128** [CompositionalIT/farmer#123]
Hi there,

First thanks to the great works.

May I know how to add resource to existing resource group? When I try to `Deploy.execute` my deployment, it just tell me something like `Invalid resource group location 'aaa'. The Resource group already exists in location 'bbb'`

**Comment by isaacabraham** [comment]
This suggests that you're creating the resource group in Farmer in a different location to the existing one? What location does the existing RG exist in?

Something doesn't feel right. As far as I know, in Azure you can have multiple resource groups with the same name but in different locations and / or different subscriptions.

**Comment by clement128** [comment]
I think now is always trying to create new group by the provided group name? Correct me if I am wrong .

**Comment by clement128** [comment]
BTW: this is the definition I had tried before

https://github.com/CompositionalIT/farmer/issues/125#issuecomment-619597423

**Comment by isaacabraham** [comment]
@clement128 apparently you can't have two resource groups with the same id in the same subscription. so i'm not sure how this would happen!

**Comment by clement128** [comment]
hi @isaacabraham  yes I know the group id must be unique, but I just want to add the resource to existing resource group. Did I do something with this?

**Comment by isaacabraham** [comment]
If you pick the name of the existing resource group and ensure it does to the same subscription it should just work? Or are you setting two resource groups with the same name in the same subscription?

**Comment by clement128** [comment]
Nope I didn't, but later I will try it again with the latest version, will update you.

thanks for the help

**Comment by isaacabraham** [comment]
No problem, I am definitely interested in this one.

**Comment by isaacabraham** [comment]
@clement128 I think this might be you deployed the same resource group but to a different subscription. Is that possible? If you try to create an RG to a different location in the same sub as one that already exists, Azure rejects the request.

**Comment by isaacabraham** [comment]
Unless this is still cropping up, I'm inclined to close this issue.

**Comment by clement128** [comment]
Hi @isaacabraham as I test it's working on the following version
- Farmer 0.21.0
- Azure CLI 2.8.0

thanks

**Comment by isaacabraham** [comment]
@clement128 I think the issue is most likely that it was picking up different subscriptions and deploying to them. Perhaps something we could add to Farmer is to emit the selected subscription out during deployment.

**Comment by ctolkien** [comment]
> Perhaps something we could add to Farmer is to emit the selected subscription out during deployment.

Would love this. The first time I used the `deploy` function in Farmer, I had _no_ idea where those assets were deployed! (I have a lot of tenants/subs that we manage).
