### ISSUE TITLE
Create contributor tutorial

### ISSUE THREAD

**Issue by dburriss** [CompositionalIT/farmer#128]
I wanted to open a discussion on creating a tutorial page for orienting a potential new contributor on how to create a new resource.
I created something similar for Terraform but the idea of creating all the CE that people would need led me to abandon the idea.
This project just focuses on Azure but that is still a lot of services just to cover the 80% of use cases.

Anyway, that is my rambling way of saying that making it easy for people to contribute their use case would help expand the supported services.

I captured the steps I followed.

Firstly, encourage them to implement the simplest thing that covers their needs.

From a code point of view... I made the following notes while implementing the ContainerRegistry.

**Requirements** 
- minimum version is 2.3.1 of Azure CLI

**Steps**
Step 1: Check feature does not already exist then open an issue asking about progress on feature and whether you want to pick it up.
    Result1: https://github.com/CompositionalIT/farmer/issues/48
Step 2: Find a good template to see structure and glean DU for options like SKUs
    Result1: https//docs.microsoft.com/en-us/azure/templates/microsoft.containerregistry/2017-10-01/registries
    Result2: https://github.com/Azure/azure-quickstart-templates/tree/master/101-container-registry-geo-replication
Step 3: Define DU types found in step 2
Step 4: Define config type
Step 5: Define builder for CE
Step 6: Define Resource type in Farmer.fs. Add to SupportedResources
Step 8: Converters + Outputters
Step 9: Add to Writer
Step 10: Tests

Obviously, if they want to TDD this... go ahead. Although I often start with tests, starting with a script file of what I wanted to look like is often a better approach. 

Covering some advanced topics might also be good here. The only one that comes to mind here as something I am unsure about but need to figure out is `dependsOn`.

I am happy to create an initial draft of this doc but thought I would dump this and get some feedback first.

Thoughts?

**Comment by isaacabraham** [comment]
Works for me! Maybe create a `contributing.md` file and let's see where it goes from there?

**Comment by dburriss** [comment]
@isaacabraham here is what I have so far for the contributions. Let me know if you think it is useful. Preferably I wouldn't make too many changes and it can evolve.

https://github.com/dburriss/farmer/blob/contributing/contributing.md
