### ISSUE TITLE
Create docs for resources missing docs

### ISSUE THREAD

**Issue by dburriss** [CompositionalIT/farmer#131]
Off the top of my head:
- I still need to do for my PR of Container Registry
- Container Group

@isaacabraham  Unless you want them in separate PRs I can submit both under this ticket?

I will go through an check if any else are missing.

**Comment by dburriss** [comment]
Just checking. All I need to do is create the 1 .md file per resource for the docs? Everything else is handled by convention?

**Comment by dburriss** [comment]
Another idea on this :)
As the number of resources grows, alphabetical ordering will become more important but keeping exact or will be tedious.
How about:
a = weight 1
b = weight 2
etc. ?

**Comment by isaacabraham** [comment]
Mmmm, not a bad idea :-)
