### ISSUE TITLE
Sln and folder structure mismatch

### ISSUE THREAD

**Issue by dburriss** [CompositionalIT/farmer#132]
Currently, there is a mismatch between the folder structure of the solution and what is shown in an IDE Solution explorer.

Folder view:
/src/Farmer/
/src/SampleApp/
/src/Samples/
/src/Tests/

Solution view:
src/Tests
Farmer
SampleApp

I am not sure if this was on purpose or the consequence of working mostly in folder view of VS Code?

Suggestion

Folder view:
/src/Farmer/
/samples/SampleApp/
/samples/Scripts/
/src/Tests/ (or /test/Farmer ? ... honestly I don't think /test/ folder is necessary since this is a very small project)

Solution view:
Tests
Farmer
samples/SampleApp
samples/ script links

The idea on the solution view here is it keeps the 2 projects that are touched most shallow in the structure. It is a small library with few projects, the simpler the better.

**Comment by dburriss** [comment]
I will create a PR for this if the suggestion is acceptable to you @isaacabraham ? Feel free to assign this to me.

**Comment by isaacabraham** [comment]
Sounds good to me!

**Comment by dburriss** [comment]
@isaacabraham I hope you don't mind that I addressed the solution restructure and making it work in 1 PR (2 different commits) but they are both cleanup of paths. 2 birds, 1 stone.
