### ISSUE TITLE
AutoOpen causes ambiguity between common types

### ISSUE THREAD

**Issue by dburriss** [CompositionalIT/farmer#133]
AutoOpen on the features means common types like Sku cases are subject to compiled last.
Since [&lt;AutoOpen&gt;] is on the Builder files, even when using a single resource you could not use a Sku of Basic unless by chance it was the resource for the last builder in the project. When Basic shows up in Intellisense but then does not work it is a little unexpected. It would be more expected if I explicitly opened a resource namespace.

Comment from @isaacabraham in issue #127 
> I'm tempted to simply put [&lt;RequiredQualifiedAccess&gt;] on all of them and ensure that they all have different type names e.g. StorageSku instead of just Sku. What do you think? The [&lt;AutoOpen&gt;] was designed to aid discoverability insofar as people can just open Farmer.Resources and get access to everything. Maybe that was a mistake.

I would be a fan of removing the `AutoOpen` but that still would not solve the issue if 2 resource with `Sku` of `Basic` were in scope. 

**Proposal**: Add `[<RequiredQualifiedAccess>]` to the DUs that are used as enum types throughout the project. 

@isaacabraham let me know if you happy to proceed in that direction and I can PR it.

**Comment by isaacabraham** [comment]
Do you mean apply `RequireQualifiedAccess` to the DUs?

**Comment by dburriss** [comment]
Yes sorry. Corrected the proposal.

**Comment by isaacabraham** [comment]
Then yes, please do :-)

**Comment by dburriss** [comment]
I just wanted to confirm before pressing on with this. The proposal is for ALL DU types used in any config.

What about the Common ones?

**Comment by isaacabraham** [comment]
Good question. Not sure - happy for you to take a view on this as you're doing it. Location and others like that I think don't really need qualified access - my thoughts were around the Sku ones to start with as they are all so similar in name.

**Comment by dburriss** [comment]
Initially was just thinking of this in terms of SKU but obviously it is not.
I will go with all resource DUs NOT in Common first and we see what that looks like in a more complex example.

**Comment by isaacabraham** [comment]
I would suggest starting just with Sku, then see what else is there. If we can avoid putting fully-qualified required everywhere, that would be better, I think, from a usability perspective.

**Comment by dburriss** [comment]
@isaacabraham when you get a chance please take a look through the PR. I submitted as a draft as I see an issue with the referencing of 2 Skus.
For WebApp and AzureSql there is a `module Sku` with values for the sku.
I could rename, but `WebAppSku` is already taken...
Anything else BUT `WebAppSku` would not be unexpected. Same goes for SQL.
I have not dug into the WHY of this so I cannot comment too much. Using both WebApp and Sql in a template would result in ambiguity I imagine.

My recommendation... hesitantly as I have not dug in but:
If the module is the public-facing access then let us rename the DU to `WebAppSkuInternal` (open to better names) and the `module` to `WebAppSku`.

**Comment by dburriss** [comment]
@isaacabraham The PR is good to go except I still am not sure how to proceed with above comment. Thoughts?

**Comment by isaacabraham** [comment]
I'm happy to merge in and then refactor - the main thing is getting the explicit types needed  :-)
