### ISSUE TITLE
Script files are tailored for running on Windows only

### ISSUE THREAD

**Issue by dburriss** [CompositionalIT/farmer#134]
The references to DLLs use `\` instead of `/`. This means they do not work on *nix based machines.

**Comment by dburriss** [comment]
I can create a PR to fix these for all fsx files. It is a quick fix and I can PR it, just assign to me.

**Comment by isaacabraham** [comment]
Yep, theres no need for paket or anything if you just want to #r the two DLLs directly (Farmer and Newtonsoft).
