### ISSUE TITLE
Support for PostgreSQL service

### ISSUE THREAD

**Issue by hravnx** [CompositionalIT/farmer#147]
Currently Farmer has support for SQL Service, but not pg - if I wanted to add support myself (and do a PR, obviously) where would I start? Any guidance?

**Comment by isaacabraham** [comment]
@hravnx Hey! @dburriss is putting together a contributions guide - and we're kind of in the middle of a big refactor of the internals - but for now I would say the best way to start is:

1. Get a hold of the ARM documentation for PG e.g. [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/allversions) and maybe an example e.g. [here](https://github.com/Azure/azure-postgresql/tree/master/arm-templates).
1. Pick a sample and start by seeing if you can write a function that can create an object that maps 1:1 with the JSON. [Here](https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Farmer.Resources.fs#L658) is the equivalent for the SQL Server resource.
1. See if you can then plug that into this [helper function](https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Builders.Arm.fs#L6) which will allow you to then test out your new resource directly from the Farmer top level.
1. Parameterise and create formal IResources for each ARM resource in the official spec e.g. servers, servers/databases, servers/firewallrules etc.
1. Create a "config" record that represents a logical abstraction across all the ARM resources and implement the IResourceBuilder interface on it.
1. Create a top-level computation expression that makes it even easier to construct.

Totally happy to support you as you go.

**Comment by dburriss** [comment]
@hravnx you can find the current version here.
https://github.com/dburriss/farmer/blob/contributing/contributing.md
I will update it this weekend with the latest refactorings.

**Comment by isaacabraham** [comment]
@dburriss Feel free to merge that into master. I can then keep it upto date in any branches where I make (sometimes sweeping) refactorings without undoing your hard work.

**Comment by dburriss** [comment]
Will do. Updating with the new direction and names from big reactors. Explaining it helps solidify it in my head.
