### ISSUE TITLE
PostgreSQL docs

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#157]
@hravnx would you be interested in having a crack at the docs for the PostgreSQL builder? Happy to help - we should probably add to the contributions guide.

**Comment by hravnx** [comment]
Of course. Is it ready to pull again, with the refactoring you were going to do?

**Comment by hravnx** [comment]
Oh, I see you’ve release. Never mind my question :-)

**Comment by isaacabraham** [comment]
Yes, all good to go! The refactorings are in. I've updated the contributions guide but it still needs more work. Of course, feel free to enhance the builder / arm resource to support databases as well :-)

**Comment by hravnx** [comment]
Sure, I’ll have a go - I’m fairly busy over the next couple of days, but I’ll get to it over the weekend. Just so you know I haven’t forgotten :-)

**Comment by hravnx** [comment]
I've created pull request #170 just documenting what's there - I will get to the extra stuff this weekend - I just quickly want to state for the record that it's slightly cumbersome to have the docs on a separate branch. It would be nicer if it was possible to submit docs along with the features that they are supposed to document.

**Comment by isaacabraham** [comment]
That's something we were considering a while back. Maybe we can do that at some point :-) Create an issue for it?
