### ISSUE TITLE
container instance - can't set "name"

### ISSUE THREAD

**Issue by JordanMarr** [CompositionalIT/farmer#161]
I am trying to create a `containerInstance` (as shown in this [pull request](https://github.com/CompositionalIT/farmer/pull/43/files#diff-7fb6e2ba4e02ca360de6dfb82fcf2b4d) by @ninjarobot).

I could not find a `containerInstance` builder, but I did find `container` (which I am assuming is the same thing).

My problem is that when i try to set the `name` property I get "This control construct may only be used if the computation expression builder defines a 'For' method.

**Comment by isaacabraham** [comment]
The old schema is out of data, you can now do the container group and instance in a single builder, see https://compositionalit.github.io/farmer/api-overview/resources/container-group/

**Comment by JordanMarr** [comment]
I saw that, but I am trying to accomplish something slightly different:
I have a container that runs a short batch script once per hour, so i want to dynamically create a container group, launch the container instance within it, and then tear down the container group — and I will do the group creation and tear down dynamically via either an azure function or a logic app. 
So in my scenario, i don’t want to create the container group ahead of time — i will create the container instance by itself in the arm template. 
So in Azure portal i just create the azure container instance with no group.

**Comment by isaacabraham** [comment]
Mmmm, that's an interesting case. That sounds like there's a few options:

1. Provide a "group only" builder. That shoudn't be too hard.
2. Just create the Farmer.Arm.ContainerInstance.ContainerGroup record manually and pass that into Farmer's add_resource method directly (or use the AsBuilder helper function to make it play nicely with the location). This is probably not as nice as option 1 but might be a reasonable solution that you can get working immediately?

**Comment by JordanMarr** [comment]
I was thinking it would need to be a "container only" builder since I will create the groups at runtime.
Maybe a separate `Builders.ContainerInstance.containerInstance` builder?

**Comment by JordanMarr** [comment]
I think this may be a non-issue.  I am used to creating a "Container Instance" via the portal, and so the fact that the docs call it a "Container Group" had me confused.  I do realize the a Container Instance runs in a group, but that's kind of an implementation detail IMO.  It seems like it should be called "Container Instance" in the docs instead of "Container Group".

**Comment by JordanMarr** [comment]
Ok, so looking back at the original [pull request](https://github.com/CompositionalIT/farmer/pull/43/files#diff-7fb6e2ba4e02ca360de6dfb82fcf2b4d) I see that it was in the parent [ children ] style:
```
let myContainerGroup = containerGroup {
    name "appWithHttpFrontend"
    os_type Models.ContainerGroups.ContainerGroupOsType.Linux
    add_tcp_port 80us
    add_tcp_port 443us
    restart_policy Models.ContainerGroups.ContainerGroupRestartPolicy.Always
    add_containers [
        containerInstance {
            name "nginx"
            image "nginx:1.17.6-alpine"
            ports [ 80us; 443us ]
            memory 0.5<Models.ContainerGroups.Gb>
            cpu 1
        }
        containerInstance {
            name "fsharpApp"
            image "myapp:1.7.2"
            ports [ 8080us ]
            memory 1.5<Models.ContainerGroups.Gb>
            cpu 2
        }
    ]
}
```

And then it was refactored to this style again (similar to what we discussed with Cosmos DB) where each container is broken out:
```
let nginx = container {
    group_name "appWithHttpFrontend"
    os_type Linux
    add_tcp_port 80us
    add_tcp_port 443us
    restart_policy ContainerGroup.RestartPolicy.Always

    name "nginx"
    image "nginx:1.17.6-alpine"
    ports [ 80us; 443us ]
    memory 0.5<Gb>
    cpu_cores 1
}
```

It's like three views of a secret!  There's the real thing, my idea of the real thing, and then various other abstractions.  

But I'm slowly getting it...
