### ISSUE TITLE
Cosmos DB Missing "Unique Key"

### ISSUE THREAD

**Issue by JordanMarr** [CompositionalIT/farmer#162]
I don't see the ability to add unique key(s) to a Cosmos DB container.
Maybe I can add this if it is not already in progress?  

```
cosmosContainer {
    name "people"
    partition_key [ "/id" ] CosmosDb.Hash
    add_unique_key [ "/name" ]
}
```

**Comment by isaacabraham** [comment]
Is that the same as adding an `index` in cosmos or something in addition to that? Indexes are supported: https://compositionalit.github.io/farmer/api-overview/resources/cosmosdb/

**Comment by JordanMarr** [comment]
No, it’s a separate section from the indexes called uniqueKeyPolicy. I created samples with both one and two unique keys and verified the resulting xml.
