### ISSUE TITLE
Support for ServiceBus Topics

### ISSUE THREAD

**Issue by sWW26** [CompositionalIT/farmer#165]
Would be nice to be able to create topics
https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/2017-04-01/namespaces/topics

Also would be nice to be able to build the service bus namespace separately so it can be passed into both queues & topics.

I'm not sure what the builders should be called, `serviceBus` is currently used for the queue + namespace combination.  Could maybe have `serviceBusTopic`, `serviceBusQueue`, `serviceBusNamespace`?

**Comment by evilpilaf** [comment]
I'd like to implement this, I noticed the same missing resource a moment ago, but the question is on how we should name this builder... I like the clarity of splitting it into `serviceBusTopic` `serviceBusQueue` and `serviceBusNamespace`

**Comment by isaacabraham** [comment]
Good question. I knew topics would eventually come up :-)

Few options:

1. We break out namespace into its own builder. This works for more complex usages than single queue / topic.
2. We make the existing service bus support topics and queues with a couple of custom keywords e.g. add_queues and add_topics, which themselves can be implemented through builders, records or even just functions.
3. We make topics work just like queues now in that they can create both the topic and, optionally, the namespace. if you already have a topic or queue, you can link_to_namespace as queues do now.
