### ISSUE TITLE
Support for standalone AppInsights

### ISSUE THREAD

**Issue by Dzoukr** [CompositionalIT/farmer#17]
This one should be quite easy, but I am not so skilled with ARM templates yet.

It would be really hand to have possibility to create standalone instance of AppInsights using comp. expression and have other parts depend on it and use its key. For example in our scenario we have a webApp and functionApp and want them both to be logged by same AppInsights where we need to setup InstrumentationKey.

**Comment by isaacabraham** [comment]
Yep, can definitely add that and that's a good use case 😊

**Comment by isaacabraham** [comment]
Note that currently if by default the template will try to create an AI instance automatically for a webapp or functionsapp and will link them together. It'll also set an app setting with the instrumentation key automatically.

Would it be easier to simply have this:

```fsharp

let myWebApp = webApp {
    name "mysuperwebapp"
    app_insights_name "myappinsights" // same name as above
}

let myFunctionsApp = functions {
    name "myFunctionsApp"
    app_insights_name "myappinsights" // same name as above
}

arm {
    location NorthEurope
    add_resource myFunctionsApp
    add_resource myWebApp
}
```

And then Farmer automatically just creates a single resource and ties them all together?

**Comment by Dzoukr** [comment]
Yes, I like it. Maybe this could be the easiest way. 
Just thinking out loud... shouldn't there be an third option? Because you can create new AI (`app_insights_name "my-ai"`), you can skip it (`no_app_insights`), but cannot reuse (or link-to) existing one?

**Comment by isaacabraham** [comment]
That's the last bit that isn't properly support yet, yes :-)

**Comment by isaacabraham** [comment]
There's sort of support for that - storage account has the same thing - but yes that needs to be tested out and thought through. I'm creating a dedicated AI builder object (it's very simple as there are no config options on AI ARM elements anyway).

**Comment by isaacabraham** [comment]
@Dzoukr I've just pushed a change to master that does the following:

1. Implements a basic AppInsights builder.
2. Adds a "distinct" check towards the end of the Arm Builder pipeline so if two resources of the same type have the same name, it only takes the first one. This means you can do the code sample above and it should just work.

**Comment by Dzoukr** [comment]
Thank you!!!!
