### ISSUE TITLE
Farmer.Template generate incorrect Program.fs

### ISSUE THREAD

**Issue by Samuel-Dufour** [CompositionalIT/farmer#185]
Hi, I just tried to create a new project using Farmer.Template.
Unfortunately the generated Program.fs doesn't compile.
Replacing its content by the one shown in the documentation fix the issue.
I think the template should be fixed to avoid beginners frustration.

For information, here are both versions.

**Generated version** :

```fsharp
open Farmer
open Farmer.Resources
open Farmer.Deploy
open System

// Create ARM resources here e.g. webApp { } or storageAccount { } etc.
// See https://compositionalit.github.io/farmer/api-overview/resources/ for more details.

// Add resources to the ARM deployment using the add_resource keyword.
// See https://compositionalit.github.io/farmer/api-overview/resources/arm/ for more details.
let deployment = arm {
    location NorthEurope
}

printf "Generating ARM template..."
deployment |> Writer.quickWrite "output"
printfn "all done! Template written to output.json"
```

[Documented version](https://compositionalit.github.io/farmer/quickstarts/template/)

```fsharp
open Farmer
open Farmer.Builders

let deployment = arm {
    location Location.NorthEurope
}

printf "Generating ARM template..."
deployment |> Writer.quickWrite "output"
printfn "all done! Template written to output.json"
```

Hope it helps !

**Comment by isaacabraham** [comment]
@Samuel-Dufour I've just released a new version of the template which fixes all of this (I hope!) :-)

**Comment by Samuel-Dufour** [comment]
@isaacabraham Fix confirmed ! Thanks ! :-)
