### ISSUE TITLE
Allow creating a VM on an existing vnet instead of creating one

### ISSUE THREAD

**Issue by Tarmil** [CompositionalIT/farmer#187]
The `vm` resource currently always creates a dedicated vnet and subnet. It would be very useful to be able to instead only give a subnet resource name, which can be an existing one (or created separately).

**Comment by isaacabraham** [comment]
What does "or created separately" mean - do you mean created separately through Farmer?

**Comment by isaacabraham** [comment]
Also - do you need to be able to specify the subnet name / range?

**Comment by Tarmil** [comment]
> What does "or created separately" mean - do you mean created separately through Farmer?

That's what I had in mind, but I suppose that would require having `vnet` and `subnet` resource builders.

> Also - do you need to be able to specify the subnet name / range?

My initial idea was to just pass an existing subnet name, and that subnet's definition (wherever it is located) defines its containing vnet and its range. But it's probably also a common use case to have an existing vnet and to need to create a subnet by specifying a vnet name and a range. So maybe we could add two operations to the `vm` builder:
* `subnet_name (ResourceName)` would associate the vm with the given existing subnet, without creating anything new;
* `vnet_name (ResourceName)` would create a subnet (using the existing `subnet_prefix` as range) and associate it with the given existing vnet.

**Comment by isaacabraham** [comment]
That's more or less the conclusion I came up to yesterday when I was trying to add this. The VM needs to know the subnet, and the subnet is created as part of the vnet. I'll finish it off this weekend and PR in.

**Comment by isaacabraham** [comment]
@Tarmil does #190 look about right/

**Comment by Tarmil** [comment]
> The VM needs to know the subnet, and the subnet is created as part of the vnet.

Actually, it looks like it's possible to create the subnet independently on an existing vnet: https://github.com/Azure/azure-quickstart-templates/tree/master/101-subnet-add-vnet-existing

Regardless, #190 looks good to me! Maybe I'll do a subsequent PR to add a subnet resource.

**Comment by isaacabraham** [comment]
Cool, I'll merge that in then!
