### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by et1975** [CompositionalIT/farmer#19]
Please specify the license.

**Comment by forki** [comment]
Any preferences?

**Comment by et1975** [comment]
Something that would let me try it w/o violating any laws, but my present employer likes MIT for some reason.

**Comment by isaacabraham** [comment]
Please submit a PR with a suitable license. I have no preference either way.

**Comment by forki** [comment]
I think MIT is good.

Isaac Abraham <notifications@github.com> schrieb am Fr., 27. Sep. 2019,
20:46:

**Comment by isaacabraham** [comment]
@CaringDev all done. looking forward to feedback :-)
