### ISSUE TITLE
Change PostgreSQL builder database handling

### ISSUE THREAD

**Issue by hravnx** [CompositionalIT/farmer#197]
Update the PostgreSQL builder to mirror recent changes to the Azure SQL builder.

**Comment by isaacabraham** [comment]
@hravnx this is probably the last thing for v1. Do you think you'll have an opportunity to do this this week? If not I can have a crack.

**Comment by hravnx** [comment]
Oh, sorry, I was not aware that this was holding the v1 up - sorry about that. I've been very, very busy, and it's been summer, bla bla excuses, excuses :-)

I'll look at it tomorrow evening.

**Comment by isaacabraham** [comment]
Hey :-) It's not holding it up - we can always push this back to a later release. But I'd love to get it in. If you don't have time, don't worry, I'll do it.

**Comment by hravnx** [comment]
No, it's fine, I have a bit of time this week, I'll do it tomorrow.
