### ISSUE TITLE
Add support for web app slots

### ISSUE THREAD

**Issue by sWW26** [CompositionalIT/farmer#198]
https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-02-01/sites/slots

Would also be useful to be able to make app settings "slot sticky".  I can't find any official documentation or reference but I've been using the following in my ARM templates.

```
{
  "name": "[variables('webAppName')]",
  "type": "Microsoft.Web/sites",
  "apiVersion": "2016-08-01",
  "location": "[resourceGroup().location]",
  "properties": {
    "serverFarmId": "[variables('appServiceResourceId')]",
    "siteConfig": {
      "connectionStrings": [
        {
          "name": "Database",
          "connectionString": "[variables('sqlConnectionString')]",
          "type": "SQLAzure"
        },
        {
          "name": "ServiceBus",
          "connectionString": "[variables('serviceBusConnectionString')]",
          "type": "Custom"
        }
      ],
      "appSettings": [
        {
          "name": "ASPNETCORE_ENVIRONMENT",
          "value": "[parameters('aspNetEnvironment')]"
        },
        {
          "name": "AllowedOrigins",
          "value": "[variables('allowedOrigins')]"
        }
      ]
    }
  },
  "resources": [
    {
      "type": "config",
      "name": "slotconfignames",
      "apiVersion": "2016-08-01",
      "properties": {
        "connectionStringNames": [
          "Database",
          "ServiceBus"
        ],
        "appSettingNames": [
          "ASPNETCORE_ENVIRONMENT",
          "AllowedOrigins"
        ]
      },
      "dependsOn": [
        "[variables('webAppName')]"
      ]
    }
  ]
}
```

**Comment by isaacabraham** [comment]
@sWW26 where is the stickyness specified to a slot here?

**Comment by sWW26** [comment]
@isaacabraham in trying to simplify the example I ended up making it invalid!  Expanded it a bit to 1. make it valid & 2. give some context.

Anything that is listed in the slotconfignames resource is counted as sticky, anything not listed is not.
![image](https://user-images.githubusercontent.com/6764717/83902093-b2ac9380-a753-11ea-9fd8-6f5bb819a6aa.png)

**Comment by isaacabraham** [comment]
ok! So is this why there are two ways to create settings in ARM? :-)

**Comment by isaacabraham** [comment]
Note from the above - there's currently no support for connection string settings in Farmer.

**Comment by isaacabraham** [comment]
@sWW26 should this be part of a bigger thing which is about modelling deployment slots as well? I'm unsure how this should manifest itself without that. Would this be part of setting the value of the setting or a separate keyword which simply says "these settings are sticky"?

**Comment by sWW26** [comment]
> Note from the above - there's currently no support for connection string settings in Farmer.

I noticed but we've discovered we don't really need to use it for our purposes anyway, can just use `ConnectionStrings: Database` instead in the app settings.

> @sWW26 should this be part of a bigger thing which is about modelling deployment slots as well? I'm unsure how this should manifest itself without that. Would this be part of setting the value of the setting or a separate keyword which simply says "these settings are sticky"?

I think adding just the sticky setting thing only doesn't make sense. If you like I can try and put a PR together with some basic setup. I'm thinking having a `slots` function on the builder which takes a list of slots built using their own builder (looks very similar to the webApp builder).

**Comment by fraxu** [comment]
I'm currently using the following quick hack to get slots working.

```
type Slot =
    { Name : ResourceName
      Location : Location
      SiteName: ResourceName
      ServicePlanName: ResourceName
      AutoSwapSlot: Slot option }
    interface IArmResource with
        member this.ResourceName = this.Name
        member this.JsonModel =
            {| name = sprintf "%s/%s" this.SiteName.Value this.Name.Value
               ``type`` = "Microsoft.Web/sites/slots"
               apiVersion = "2020-06-01"
               location = this.Location.ArmValue
               tags = {||}
               properties = 
                    {| serverFarmId = this.ServicePlanName.Value
                       siteConfig = 
                       {| autoSwapSlotName = this.AutoSwapSlot |> Option.map(fun s -> s.Name.Value) |> Option.toObj |} 
                    |}
            |} :> _

let testWebApp = webApp {
    name "test"
    sku WebApp.Sku.S1
}

let productionSlot = 
    { Slot.Name = ResourceName "production"
      SiteName = testWebApp.Name
      ServicePlanName = testWebApp.ServicePlanName
      Location = Location.WestEurope
      AutoSwapSlot = None }

let stagingSlot =
    { Slot.Name = ResourceName "staging"
      SiteName = testWebApp.Name
      ServicePlanName = testWebApp.ServicePlanName
      Location = Location.WestEurope
      AutoSwapSlot = Some productionSlot }

let deployment = arm {
    location Location.WestEurope
    add_resource testWebApp
    add_resource stagingSlot
    add_resource productionSlot

```

For basic slots support I guess we would need at least:
* Custom operator in WebApp builder to make adding slots easy
* autoSwapSlotName to Site Arm as well
* Slot builder?
* Documentation

I'm happy to help with this if needed!

**Comment by isaacabraham** [comment]
This is awesome :-) Great to see the extensibility API working for you.

To be honest, in terms of the user-facing API I think just a custom operator would be enough - do we really need an extra builder on top as well e.g.

```fsharp
let testWebApp = webApp {
    name "test"
    sku WebApp.Sku.S1
    add_slots [ "production"; "staging" ]
}
```

Behind the scenes, the web app builder would create the appropriate slots as required (of course, the IArmResource that you've constructed would need to be added in as well).

Settings could be a secondary piece of work - we would probably need an overload or new keyword for settings e.g. `slot_setting` which took in the key / value AND the slot name.

**Comment by TheRSP** [comment]
I think the additional keyword for slots would be great but how would `zip_deploy` work with slots?
Would something like the following be possible? 
```fs
let testWebApp = webApp {
    name "test"
    sku WebApp.Sku.S1
    add_slots [ "production"; "staging" ]
    zip_deploy "staging" "./My.App.zip" //Upload the given zip file to the 'staging' slot
    swap_slots "staging" "production" // Swap the named slots - needs to happen after zip_deploy
}
```

**Comment by TheRSP** [comment]
@isaacabraham I should have a little bit of time coming up and this will soon be a priority for my company.

What do you think about adding these new keywords?
- `slots` - takes a string list of slot names (overrides any previous value)
- `zip_deploy_slot` - takes a slot name and zip path to deploy to the given slot

Further improvements could then be to add
- `add_slot_setting`/`add_slot_settings` for sticky settings
- `add_slot_connection_string`/`add_slot_onnection_strings` for sticky connection strings

Is there an alternative API you would prefer?

**Comment by JordanMarr** [comment]
No slots support yet? 😢

**Comment by isaacabraham** [comment]
@JordanMarr it's been open for anyone to add this whenever it was needed.
@TheRSP looks good for a start, will maybe be a breaking change for `zip_deploy` though. Maybe other ways to solve that.

**Comment by JordanMarr** [comment]
🤡🤡🤡
