### ISSUE TITLE
Configure Managed Identity and CORS

### ISSUE THREAD

**Issue by et1975** [CompositionalIT/farmer#205]
Any guidance on how to set those up for a function?

**Comment by isaacabraham** [comment]
@et1975 Managed Identity is ready in a PR - currently only for web apps but it will be very easy to add to functions. CORS - if you have an example of how to do this in ARM it can be added.

**Comment by et1975** [comment]
Isaac, here's what it should look like in arm: https://stackoverflow.com/questions/46921887/azure-functions-how-to-set-cors-via-automation

**Comment by et1975** [comment]
Thanks!
