### ISSUE TITLE
How to support private container registry for Container Groups

### ISSUE THREAD

**Issue by clement128** [CompositionalIT/farmer#210]
hi there, may I know how to use private container registry for deploy to container group?

I am getting this error
```json
 "error": {
    "code": "InaccessibleImage",
    "message": "The image 'xxx' in container group 'ForTesting' is not accessible. Please check the image and registry credential."
  }
```

**Comment by isaacabraham** [comment]
@dburriss @forki have you done this? I think currently we only support ACR but I might be wrong here.

**Comment by dburriss** [comment]
I would need to look into it more as have not done it myself but I believe the Farmer resource needs support for `networkRules`. I need to confirm but I could add it once I have confirmed that is all that is needed.
