### ISSUE TITLE
Slack callouts for doc pages have an autogenerated slug

### ISSUE THREAD

**Issue by baronfel** [CompositionalIT/farmer#232]
![image](https://user-images.githubusercontent.com/573979/84922086-fd4ed980-b08a-11ea-925a-4ca0ee2d5ec4.png)

Here you can see the auto-generated content slug "Documentation for the Hugo Learn Theme". I think ideally each page would have a front-matter summary that would appear here instead.

**Comment by isaacabraham** [comment]
Thanks - I thought I'd fixed this but evidently not!

**Comment by isaacabraham** [comment]
Fixed

**Comment by isaacabraham** [comment]
Fixed.
