### ISSUE TITLE
Parameterized Logic App for loading a container instance

### ISSUE THREAD

**Issue by JordanMarr** [CompositionalIT/farmer#243]
I have created a Logic App that is responsible for scheduling and running a containerized batch process.  

It handles the following:
- Triggers by timer
- Pulls container from Azure Container Registry
- Creates and runs a container group with configured name
- Polls to see if container group creation has succeeded and also if container instance is terminated (completed)
- Deletes the container group

This is a pretty common use case, and you can accomplish it either with an Azure Function or a Logic App.  I went with the Logic App because Azure Functions currently do not support .fsx files, and I didn't want to create an entire Azure Functions project just to create and delete a container instance.

The Logic App, despite being billed as "simple", was actually kind of annoying to get right, as none of the examples worked correctly.

I think it would be a very nice value proposition for this to be added to Farmer as a sort of "higher level template / orchestration / common task set". Not sure what you would want to call it, but I can imagine other common Logic App scripts would be useful value adds as well.  

While it would be nice to have the entirety of Logic Apps encoded in farmer, I think that could also be a never ending quagmire.  Plus, it seems unrealistic for Farmer to try to compete on that level of "full" coverage with alternative frameworks.  
Rather, I think that having a few choice pre-made Logic App scripts like this one could be very useful.  If I could have configured 6 lines of code in Farmer to build, poll and clean up my container, rather than spending 5 hours building a custom Logic App or custom Azure Function, I would have been better off for it!

I imagine the most simple implementation would be for me to just parameterize the json in the most straightforward way possible.   Then later it could possibly be refactored into parameterized Logic App "Actions".  But I think that treating it as one monolithic configurable task would be the easiest way to start.

The parameters would be something like this:
- The timer trigger intervals (and could be upgraded to take a DU of triggers to allow other types of triggers)
- The container registry and container instance name
- The container group name that will be created by the script

**Comment by isaacabraham** [comment]
Closing in favour of #484
