### ISSUE TITLE
Support for Event Hubs Capture

### ISSUE THREAD

**Issue by vjraitila** [CompositionalIT/farmer#253]
Farmer DSL does not support enabling capture for Event Hubs. Please enable this.

https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-resource-manager-namespace-event-hub-enable-capture

**Comment by isaacabraham** [comment]
This looks like a really nice addition to have and could be done quite nicely I think.

**Comment by isaacabraham** [comment]
@vjraitila could you put together some pseudo-code here as an example of how you might like to access / consume this?

**Comment by isaacabraham** [comment]
This has now been released.
