### ISSUE TITLE
Executing a script

### ISSUE THREAD

**Issue by Thorium** [CompositionalIT/farmer#259]
I have a few questions, because the current documentation seemed a bit thin. I'd like to deploy a VM and an Azure SQL database by Farmer. Very basic software architecture. For that, I need to execute a few scripts: 

1) Virtual Machine, 
   - Execute cmd/bat/shell-script. [That is possible](https://techcommunity.microsoft.com/t5/itops-talk-blog/how-to-run-scripts-in-your-azure-vm-by-using-run-command/ba-p/1362360#:~:text=You%20can%20run%20commands%20directly,port%20or%20enable%20PowerShell%20remoting), but can that be done by Farmer?
       - Install Chocolatey `@powershell -NoProfile -ExecutionPolicy Bypass -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin`
       - Install a few programs like `choco install dotnet4.7.2 -y`
       - A way to transfer a few files. By installing SSH I guess?
       - Configure Windows firewall, e.g.: `netsh advfirewall firewall add rule name="Open Port HTTPS" dir=in action=allow protocol=TCP localport=443` 
       - Install certificate (`certutil`) and apply certificate to the port: `netsh http add sslcert ipport=0.0.0.0:443 certhash=123abc... appid=abc124...`
       - Create a service `sc create MyService binPath= c:\path\myservice.exe`
       - ...and set it to auto-start: `sc config "MyService" start= auto`
   - I also need to configure the Azure side `Network interface` for the VM, I couldn't find Farmer command for that.
   - Set a static IP for VM. I guess this is already supported.

2) Deploy the Azure Database.
      - Create a new login.
      - Execute an *.sql-script that creates the tables, and inserts some basic data. [Azure supports that](https://docs.microsoft.com/en-us/azure/azure-sql/database/connect-query-portal), but can that be done with Farmer?
      - For the database version control, I'm using VisualStudio SQL Server Database Project (*.sqlproj). Is that messing my architecture-as-code?

What is the preferred way to do these with Farmer?

**Comment by isaacabraham** [comment]
## VMs

1. Scripts - you can run a post-deployment script on a VM in an ARM template. We haven't exposed that yet in Farmer but there's no reason why we couldn't - I suggest raising an issue.
2. Transferring files - we *could* build a post-deploy task to upload files from the local machine onto the VM. The pure ARM way is to upload files into a storage account first and then reference them in the ARM template. However, this requires a storage account to have been already created and the files uploaded. An alternative is to upload via Azure CLI or SSH - again, Farmer could wrap this up; it's what we do for app service.
3. Firewall - this should be possible in ARM, I suggest looking [through the docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2019-03-01/virtualmachines) - if it's there, we can expose it. 
4. I *believe* that static IPs are already supported.

## Databases
1. I don't know if you can create separate logins within ARM - I believe it's just the standard admin login. Again, can you check the ARM docs for SQL?
2. When you say "Azure can do that" - do you mean the portal? The portal uses all sorts of different things; Farmer is essentially a wrapper around what [ARM templates](https://compositionalit.github.io/farmer/about/) support plus some extensions that wrap around the Azure CLI for things that ARM doesn't support.

Database version control and deployments are a separate concern to Farmer - it shouldn't impact infrastucture-as-code at all (indeed, we're using dbprojects right now with Farmer - it should just work.

**Comment by Thorium** [comment]
This was supposed to be the issue for "run a post-deployment script on a VM" but then I just raised other points to here as well...

I guess the SQL-part can be considered as done: SQL-script can create more logins, so that's not big problem, I can just connect to database and execute the login-creation scripts as other scripts. 

And yes, I would really much like an auto-magical upload-files system, maybe even remove the hole used to transfer after uploading, to be as secure as possible.

**Comment by isaacabraham** [comment]
@Thorium something like this? https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows

**Comment by isaacabraham** [comment]
@Thorium there's a PR to allow inline scripts if you would like to test that out (you can download and build Farmer directly from that branch and reference it directly in e.g. a script etc.).

**Comment by isaacabraham** [comment]
I've reopened this because you raised other points as well - if you want to move them to other issues and then close this one, that's fine.

**Comment by isaacabraham** [comment]
This has now been released.
