### ISSUE TITLE
Split FunctionApp & WebApp

### ISSUE THREAD

**Issue by Dzoukr** [CompositionalIT/farmer#26]
I am trying to create support for selecting runtime stack for `WebApp`, but now in code the function for creating `ArmTemplate` record considers functionApp as another "version" of WebApp. The problem is, that even if they are close together, they do not offer exactly the same options for setup.

FunctionApp:
![image](https://user-images.githubusercontent.com/851307/65907726-2e845e00-e3c5-11e9-978d-4926512d92b0.png)

WebApp:
![image](https://user-images.githubusercontent.com/851307/65907733-317f4e80-e3c5-11e9-8ef0-db61ed8f4c9d.png)

Also each template writes `Runtime Stack` in slightly different way.

FunctionApp:
```
"appSettings": [
{
  "name": "FUNCTIONS_WORKER_RUNTIME",
  "value": "dotnet"
}
```

WebApp:
```
"appSettings": ... omited
"metadata": [
 {
  "name": "CURRENT_STACK",
  "value": "dotnetcore"
 }],
```

This would force me to do another `if` logic in writer logic (where anonymous record would differ based on whether `Kind` contains `functionApp` or not), which doesn't sound too clean to me. Also thinking about adding another options like `always_on`, which is not available in FunctionApp template, the `if` would appear more than once.

Proposal: Add FunctionApp as another `SupportedResource` case (even if it is neeearly same as WebApp) and also add different Runtime stack values for each type as it is now in Azure Portal. 

Good idea, wrong idea, total nonsense? What do you think @isaacabraham?

**Comment by isaacabraham** [comment]
Hmmm, sounds like both routes might be OK :-)

Setting different fields e.g. `appSettings` or `metadata` is totally fine - that should be done in the `Run` method of the `ArmBuilder` anyway. You could set `metadata` as an optional field on the WebApp and only set it in the Functions section of `Run`. If you think that that's too "messy", then we *could* create a new Functions type, but one of the goals I had for types in `Farmer.fs` e.g. `WebApp` was to try to keep the format relatively close to what the final output would look like (minus the fluff) in terms of structure and to maintain a 1:1 relationship between these types and ARM resource types, so I'd like to avoid creating indirection there if possible.

I think adding new runtime stack DU is fine though, you can just add that on as well.

**Comment by Dzoukr** [comment]
> but one of the goals I had for types in Farmer.fs e.g. WebApp was to try to keep the format relatively close to what the final output would look like

I know what you mean... I'll try keep the current structure first (and add new DU for runtime stack) and we will see. It is fresh meat so we can still easily refactor later.

**Comment by isaacabraham** [comment]
BTW looking here I'm seeing a different schema https://docs.microsoft.com/en-us/azure/templates/Microsoft.Web/2018-11-01/sites with no mention of the Metadata node.

**Comment by Dzoukr** [comment]
The current used (at least on my subscription) is `2018-02-01`, but cannot see metada neither. :( I guess it is one of those well hidden settings. I found it when I tried to create new one manually and then checked generated template for it.

Speaking about versions... Should we "upgrade" to higher version?

**Comment by isaacabraham** [comment]
yes re: upgrade!

**Comment by Dzoukr** [comment]
Not needed anymore once branch `refactor-29` is done.

**Comment by isaacabraham** [comment]
Reopening - we can close this issue as part of the PR acceptance process :-)
