### ISSUE TITLE
Support Access Control Allow Credentials for functions and web apps.

### ISSUE THREAD

**Issue by ctolkien** [CompositionalIT/farmer#265]
```F#
enable_cors ["*"]
```

Results in:
`Unhandled exception. System.UriFormatException: Invalid URI: The format of the URI could not be determined.`

From the Azure Portal:

>To allow all, use "*" and remove all other origins from the list.

**Comment by ctolkien** [comment]
I didn't RTFM:

`WebApp.AllOrigins`

**Comment by isaacabraham** [comment]
We could either check for * and implictly convert to `AllOrigins` or at least show a better error.

**Comment by ctolkien** [comment]
There is this feature too which I don't think is exposed:
![image](https://user-images.githubusercontent.com/515955/86416226-b7417900-bd0c-11ea-9dd8-dc3c302c1966.png)

**Comment by isaacabraham** [comment]
@ctolkien does that relate to this: https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2019-08-01/sites#corssettings-object ? Or another setting? If you can show us which setting is needed we can definitely add it.

**Comment by ctolkien** [comment]
@isaacabraham - yes that maps to the  `supportCredentials` propery on the `CorsSettings` object.

I'll re-open / rename this ticket to track the work of adding that in?

**Comment by ctolkien** [comment]
I had a crack at this, whilst I might get it working, I've no idea on idiomatic F#.

**Comment by isaacabraham** [comment]
@ctolkien if you need a hand with a review etc., just let me know.

**Comment by isaacabraham** [comment]
@ctolkien are you happy to do this still?

**Comment by ctolkien** [comment]
I tried and failed, need a better grasp of F#. Will have to pass on finishing this myself.
