### ISSUE TITLE
Unable to create a static site storage account

### ISSUE THREAD

**Issue by VitorRigoni** [CompositionalIT/farmer#289]
Hello! 👋🏻

I'm writing a script to create a storage account with a static website but I don't seem to be able to do that.
I'm not sure what I'm missing, but even the sample provided in the docs is not working for me.

I keep getting: `This control construct may only be used if the computation expression builder defines a 'For' method`.

I'm referencing Farmer v0.22.

This is what my script looks like
```fsharp
let comingSoonWebsiteStorageAccount = storageAccount {
  name "coming-soon"
  use_static_website "coming-soon" "index.html"
  static_website_error_page "error.html"
}
```
I'm feeling very dumb right now because this should totally be working 😓

I appreciate any help and thank you so much for the awesome job with Farmer! 🎉

**Comment by isaacabraham** [comment]
Apologies. The docs and app are out-of-sync. The *next* release of Farmer will have those keywords. The *current* release is a little different:

```fsharp
let comingSoonWebsiteStorageAccount = storageAccount {
    name "coming-soon"
    static_website "index.html" "error.html"
    static_website_content "coming-soon"
}
```

The new version will be released later this week.
