### ISSUE TITLE
Incorporate KeyVault into WebApp builder

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#290]
In the interest of having a great "default experience" for web apps on Azure, I think we should consider - as we do with App Insights - directly building KeyVault into the webapp builder. When users try to add a secret setting, rather than it still being stored as an app setting, we would implicitly store the key in keyvault. We can also use the ability to reference keyvault secrets directly from Azure App Service app settings to make the experience seamless for the developer.

**Comment by pihai** [comment]
Hi

I tried to get the following working in Farmer:

* Create a WebApp with a managed identity
* Create a KeyVault
  * Add a secret to the vault
  * Add an access policy to the vault for the web app
* Add a key vault reference app setting to the web app

Currently this results in a circular dependency because: 
* The vault depends on the manged identity of the web app
* The web app depends on the secret uri of the vault

On way to resolve this is by using the standalone appsettings resource: https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-11-01/sites/config-appsettings

Here you can see a working prototype of this: https://gist.github.com/pihai/526b9ab05ea3f604cc5aa683a764b6c3

Is this what you are aiming for with this enhancement?

**Comment by isaacabraham** [comment]
My initial thoughts were to make this even more opaque e.g.
```fsharp
webApp {
   use_keyvault // tells the builder to create a keyvault and redirect settings etc. as required.
   setting "key" "value"
}
```

Regarding the standalone app setting - yes, I read that recently too. We've already started moving all nested resources into top-level resources and this would be another one we could / should do.

So currently you can't easily use the settings approach for app service with keyvault - you could do it in your sample by making the module recursive (at the top of your file just do e.g. `module rec MyTemplate`) but we should have a better option than that really. You could do it stringly typed as well.

**Comment by pihai** [comment]
Ok thanks. I think I begin to understand.

The same nested vs. top level resource debate may apply to key vault access policies and secets as well. Currently a key vault deplyoment always overwrites the whole vault. It is not possible to incrementally add only a single secret or access policy. With top level resources this would be possible: https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2019-09-01/vaults/accesspolicies

Using standalone top level resources resolves the circular reference problems. No need to stringify or recurisve module declarations, at least I think so.

Do you have an opinion on letting the user define e.g. a standalone app-setting resource in the template or should the Builder handle such low level details itself: 

```fsharp
let webApp = webApp {
  setting "c" "d" // i think this will be overwritten
}
let appSettings = appSettingsConfig {
  site webApp
  setting "a" "b"
}
let template = arm {
  add_resource webApp
  add_resource appSettingConfig
}
```

Here is another example where the access policy update of a key vault is a standalone resource/builder:

```fsharp
let secret = secret { ... }
let kv = keyVault {
    add_secret secret
}
let app = webApp { // depends on kv
    enable_managed_identity
    add_setting "normal_setting" "foo"
    add_key_vault_reference kv secret
}
let policy = accessPolicyUpdate { // depends on kv and app
    vault kv
    object_id app.SystemIdentity
}
let template = {
    add_resources [ secret; kv; app; policy ]
}
```

**Comment by ctolkien** [comment]
Some more nuance to throw into the mix:

* KeyVault must be created from inside the appropriate tenant to work correctly - Delegated Resource Management / Azure Lighthouse has issues here (whilst it's fine for creating webapps themselves). So I have to split these up regardless.
* I really like the managed identity bits outlined above.

**Comment by isaacabraham** [comment]
The main integration is in. I think we should create a new issue to discuss the bigger issue of the circular references.
