### ISSUE TITLE
Storage account name length restriction

### ISSUE THREAD

**Issue by pihai** [CompositionalIT/farmer#295]
The name of a storage account gets truncated to a maximum of 16 characters: 

https://github.com/CompositionalIT/farmer/blob/3fd022d39d7a7b6c75f5f21dfc8ffaabfb72e0b4/src/Farmer/Builders/Builders.Helpers.fs#L12

However the official limitation is 24 characters: [Source](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules#microsoftstorage)

Is there any reason why Farmer is more restrictive here?

**Comment by isaacabraham** [comment]
@pihai because often storage account names are postfixed in Farmer with the name of the parent builder e.g. a functions host called "foobar" may have a storage account called "bananasfoobar".

To be honest I think we may change this from silently renaming storage accounts to simply failing fast if the account doesn't conform to the storage account naming rules.

**Comment by pihai** [comment]
For me failing fast instead of silently renaming sounds like a better approach.

However, my use case was to add a file share to an already existing storage account created by hand. Unfortunately the name is longer than 16 characters. Instead of the existing storage account with an additional file share I ended up with a new storage account. 

 As I understand it, I won't be able to do that?

**Comment by isaacabraham** [comment]
We should just remove the 16 character restriction on file names. Ideally you should be able to create a storage account in Farmer which has the same name as an existing Storage Account resource and go from there.

**Comment by isaacabraham** [comment]
@pihai This is ready to go now (see the associated PR). In the meantime, you can work around this by constructing the `StorageAccountConfig` record type directly:

```fsharp
let storageAccount =
    { Name = ResourceName "mystorage"
      Sku = Storage.Premium_LRS
      EnableDataLake = false
      Containers = []
      FileShares = []
      Queues = Set.empty
      StaticWebsite = None }
```

This can be added as a resource to the `arm { }` item as normal.

**Comment by pihai** [comment]
thats great, thank you
