### ISSUE TITLE
Support for adding resource tags

### ISSUE THREAD

**Issue by tdwhite0** [CompositionalIT/farmer#298]
Unless I'm mistaken it doesn't look like there is a way right now to add resource tags to the generated template like shown here:

https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-tutorial-add-tags?tabs=azure-powershell

This would be a nice feature to have, I'm thinking about building it myself. Does anyone have any ideas on the best way to implement?

**Comment by TheRSP** [comment]
My company also need support for tags. I was wondering if adding `tag`/`tags` keywords to each of the builders would be sufficient:
```f#
webApp {
  name "my-web-app"

  tag "tier" "UI"
  tags [
    ("Favourite Colour", "Purple")
    ("Favourite Animal", "Mantis Shrimp")
  ]
}
```

**Comment by isaacabraham** [comment]
Yes, that seems reasonable. Only question is that the builder would need to decide which resources were given the tags - I suppose for some builders this would be different.

**Comment by TheRSP** [comment]
Yes, I had assumed in the above example that the tags would apply to the "main" resource (the website) but we actually have three options:
1. apply to the main resource
2. apply to all resources
3. have some way of specifying to which resources to apply the tags
  a. by using different keywords (`site_tags key value`, `server_farm_tags key value`)
  b. by using an argument (`tag Arm.Web.serverFarms key value`) optionally using 1 or 2 as a default value?

**Comment by tehmufifnman** [comment]
Additionally many resources aren't compatible with the tags field, so some way of representing that will be necessary.

**Comment by isaacabraham** [comment]
@tehmufifnman Really? I thought it was some generic thing. In that case, perhaps doing this on an ad-hoc, as-needed basis is indeed the way to go.

**Comment by tehmufifnman** [comment]
@isaacabraham Yup - I am sorta fell into the role of ARM template whisperer around my office LOL

Off the top of my head the one example that comes to mind is a Service Bus Queue/Topic Subscription.
https://docs.microsoft.com/en-us/azure/templates/microsoft.servicebus/namespaces/topics/subscriptions
(notice the lack of "tags")

If you try to add a tags field and deploy you get a validation error.

Here is the full list of tag support from Microsoft:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support

**Comment by isaacabraham** [comment]
So still a large number of resources to support. I'd say for now let's go with the builder approach - each builder will have to determine how it assigns tags to child resources e.g. for web app / functions, do the tags go on the service plan or the app service, or both etc. etc.

**Comment by isaacabraham** [comment]
I believe this can be closed now. @TheRSP thanks for the work on this one.
