### ISSUE TITLE
Add dependencies to Key Vault

### ISSUE THREAD

**Issue by pihai** [CompositionalIT/farmer#308]
Currently we cannot set dependencies for a key vault. This is needed if you want to create an access policy for the managed identity of a web app. In this scenario the web app has to be created first.

Example:

```fsharp
let webApp = {
  enable_managed_identity
}
let accessPolicy = accessPolicy {
    object_id webApp.SystemIdentity
}
let keyVault = keyVault {
      add_access_policy accessPolicy
      add_secret secret
      depends_on webApp
}
```

**Comment by isaacabraham** [comment]
Closed by #309
