### ISSUE TITLE
Create resource group

### ISSUE THREAD

**Issue by brettrowberry** [CompositionalIT/farmer#31]
One of the things I do today with ARM templates is create resource groups. Does Farmer support resource group specification? I didn’t see it in the README or the examples.

**Comment by isaacabraham** [comment]
@brettrowberry Farmer only "directly" takes reponsibility for generating the ARM template itself.

However, Farmer does have a simple helper function that delegates to the Azure CLI for deployment of the template, and that API *does* support specifying the resource group you wish to deploy to - and it will create it if it does not exist:

```fsharp
// Create a template for a web app in North Europe
let template =
    let myWebApp = webApp {
        name "mysuperwebapp"
        sku WebApp.Sku.F1
    }

    arm {
        location NorthEurope
        add_resource myWebApp
    }

// deploy the template to "my-resource-group"
template
|> Writer.quickDeploy "my-resource-group"
```

Behind the scenes `quickDeploy` emits the ARM template to a file `farmer-deploy.json`, before creating and executing the following batch file:

```bat
az login && az group create -l northeurope -n my-resource-group && az group deployment create -g my-resource-group --template-file farmer-deploy.json
```

**Comment by brettrowberry** [comment]
> that API does support specifying the resource group you wish to deploy to - and it will create it if it does not exist

Perfect!

**Comment by clement128** [comment]
Hi there, what if I don't want to create new resource group but use existing resource group instead, is there any way? 

thanks
