### ISSUE TITLE
Connection String Support

### ISSUE THREAD

**Issue by 76mel** [CompositionalIT/farmer#310]
Cannot see and connection string support in Farmer, is there a way to do it with settings?

**Comment by isaacabraham** [comment]
Currently, you can just only use Settings - there's really not much difference between the two as far as I'm aware. We could expose Connection Strings if needed as well.

**Comment by 76mel** [comment]
Yep I think it would be nice, it quite commonly used in apps we see rather than plain settings.

**Comment by isaacabraham** [comment]
@76mel out of interest, what's the real benefit we gain from using connection strings rather than plain settings?

**Comment by 76mel** [comment]
None that I can think of, I think it more legacy web.config support.
