### ISSUE TITLE
Additional storage account properties

### ISSUE THREAD

**Issue by onionhammer** [CompositionalIT/farmer#311]
It would be great to have some more common attributes on storage accounts, such as, 'tier', 'kind', and 'properties'. ~~Also Management polices for blob lifecycle management would be great~~ (moved to #312)

```F#
// Create a storage account with a container
let myStorageAccount = storageAccount {
    name storageName
    sku Storage.Premium_LRS
    // tier Premium
    // kind "BlockBlobStorage"
    //   "properties": {
    //     "supportsHttpsTrafficOnly": true,
    //     "accessTier": "Hot"
    //   },
    // managementPolicies
}
```

**Comment by isaacabraham** [comment]
Hey @onionhammer could you provide some more info on each of them - what purpose does each one serve e.g. what's the relationship between SKU and Tier - do we need both?

Regarding lifecycle management - we could model this very nicely in F#. I would create a separate issue for that though.

**Comment by onionhammer** [comment]
@isaacabraham all documented here; https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts

I *think* tier is required in order to create a premium blockblobstorage account.

Technically '**kind**' is documented as 'required': 
"Required. Indicates the type of storage account. - Storage, StorageV2, BlobStorage, FileStorage, BlockBlobStorage"

**Comment by isaacabraham** [comment]
`Kind` is [already set](https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Arm/Storage.fs#L36) as StorageV2. Are there specific use cases for expanding this to support the other kinds? My understanding is that StorageV2 is "the future" and should provide the same functionality as all of the others.

**Comment by isaacabraham** [comment]
Let me know which specific properties you think need adding - our approach for Farmer thus far has been to adopt an 80/20 approach, and when there are specific requirements to add more surface area, to do it.

**Comment by onionhammer** [comment]
@isaacabraham storagev2 is standard performance tier, 'BlockBlobStorage' is premium blob storage, which means higher performance than standard.

see this:
https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#performance-tiers

**Comment by tehmufifnman** [comment]
@onionhammer That isn't entirely accurate.  If you look at your link, Storagev2 can be Standard OR Premium (Check the Supported Performance Tiers column).  Storagev2 is the option most people will used in the vast majority of circumstances unless you need the more specialized features of something like BlockBlobStorage.  Storagev2 can be any type of storage account (Blob, File, Queue, etc...). Storagev1 is essentially legacy.  BlockBlobStorage and FileStorage are both just premium only is all.

"General-purpose v2 accounts: Basic storage account type for blobs, files, queues, and tables. Recommended for most scenarios using Azure Storage."

Checking the ARM template docs:
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-04-01/storageaccounts

SKU is used to set Tier/Replication Options, and Kind is used for setting Storagev2

**Comment by isaacabraham** [comment]
> I feel like most of this library could probably even be generated rather than hand crafted, since the structure of ARM is well known and well documented.

@onionhammer if only that were true :-) A lot of what we do is to remodel the ARM template into F# to take advantage of things like union types - the ARM spec is generally not accurate and often not correct. In fact, probably 75% of the work in creating a new resource goes into that.

We support v2 by default, I see no reason to change that, but certainly we can add the access tier and supports https only flags.

**Comment by BrianVallelunga** [comment]
> 
> 
> `Kind` is [already set](https://github.com/CompositionalIT/farmer/blob/master/src/Farmer/Arm/Storage.fs#L36) as StorageV2. Are there specific use cases for expanding this to support the other kinds? My understanding is that StorageV2 is "the future" and should provide the same functionality as all of the others.

I've been playing with Farmer for a day now and just came to see if I could create a V1 storage account. While V2 might be the future, there's a huge cost savings for V1 if you're using it as the backing for a Functions app that has millions of invocations per day.

I was doing some reorganizing of our resources a few months back and created a separate storage account just for Function/Webjob storage. I only noticed the next month that our bill was about $2000 higher than it should have been. After digging around, I noticed that I had created a V2 account and discovered that they have a huge cost increase if you're doing a lot of small IO operations (which are done by default for Webjobs/Functions). Per 10,000 writes/list/create V1 costs $0.00036 USD vs V2 at $0.05. Reads are a similar difference.

**Comment by isaacabraham** [comment]
@BrianVallelunga that's great feedback - so we should definitely add that then.

**Comment by isaacabraham** [comment]
@BrianVallelunga looking on the pricing page - https://azure.microsoft.com/en-us/pricing/details/storage/blobs/ - I can't even see the v1 pricing :-) Where is it?

**Comment by BrianVallelunga** [comment]
You have to click "Other" in the pricing offers, but here's a screenshot:

![image](https://user-images.githubusercontent.com/351190/92162766-b0b0aa00-ee00-11ea-8954-9427944b68f4.png)

**Comment by isaacabraham** [comment]
How about this:

1. We expose the full Storage Kind in the "low level" ARM Storage type:

```fsharp
type StorageAccountKind = StorageV1 | StorageV2 | BlobStorage | FileStorage | BlockBlobStorage
```

2. The storage builder will set this to StorageV2.
3. Functions and VMs (which can create storage accounts automatically if needed) will be set to StorageV1.
4. If you need to create a Storage resource outside of the builder, you can do that using the low-level ARM type e.g.:

```fsharp
let lowLevelStorage =
    { Name = StorageAccountName.Create "myaccount" |> Result.get
      Location = Location.WestEurope
      Sku = Sku.Standard_GRS
      Kind = StorageV1
      EnableHierarchicalNamespace = false
      StaticWebsite = None
      Tags = Map.empty }
```

These can be passed directly into Farmer's arm builder:

```fsharp
let template = arm {
    add_resource lowLevelStorage
}
```

We could expose the `kind` property on the builder as well - I don't mind doing that, although I'm not sure I fully understand the relationship between the sku and kind (if any?).

**Comment by isaacabraham** [comment]
@onionhammer @BrianVallelunga what do both of you think of this proposal above?

**Comment by onionhammer** [comment]
Sounds great as long as I can specify kind of "BlockBlobStorage" and tier of "Premium"!

**Comment by BrianVallelunga** [comment]
Yes, this seems reasonable to me as well. I'm definitely in the camp of "as long as it is possible" for this. I'll be getting back trying to use Farmer in production in the next two weeks so I'll hopefully be able to give it a try then.

**Comment by isaacabraham** [comment]
Great. Sorry - I just saw your responses to this. I'll target this for 1.3.

**Comment by isaacabraham** [comment]
@BrianVallelunga @onionhammer @tehmufifnman OK. So having read through the docs, this is what I see the reality of the situation in terms of relationship between SKU and Kind:

```fsharp
type Sku = Standard_LRS | Standard_GRS | Standard_RAGRS | Standard_ZRS | Standard_GZRS | Standard_RAGZRS | Premium_LRS | Premium_ZRS
type BlobStorageSku = Standard_LRS | Standard_GRS | Standard_RAGRS
type StorageAccountKind =
    | StorageV1 of Sku
    | StorageV2 of Sku
    | BlobStorage of BlobStorageSku
    | FileStorage
    | BlockBlobStorage
```

`FileStorage` and `BlockBlobStorage` don't need any options because they only support `Premium_LRS` anyway, so when we emit to ARM we can hard-code that into the emitter.

Does this all make sure? If so, I can push through a beta release next week for you to test out.

The main Storage Account builder won't change - we'll keep that "locked" to StorageV2 - but you'll be able to manually create StorageV1 resources etc. as needed.

For VMs and Functions, thinking about this, I don't really want to change that behaviour now as this would be a breaking change at the ARM level (which I'm concerned about) - but we could potentially add that as an option in the future (or in the next major release change it up).
