### ISSUE TITLE
Add lifecycle management support for storage account

### ISSUE THREAD

**Issue by onionhammer** [CompositionalIT/farmer#312]
Splitting from #311 for separate tracking;

Blob lifecycle management allows you to automatically move/archive/delete blobs

Schema documented here:
https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts/managementpolicies

More info here:
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts?tabs=azure-portal

**Comment by isaacabraham** [comment]
@onionhammer how does this look:

![image](https://user-images.githubusercontent.com/1781813/92048041-fdf03580-ed86-11ea-87d5-e738e5683321.png)

**Comment by onionhammer** [comment]
Very fsharpy, cool

**Comment by isaacabraham** [comment]
@onionhammer is it readable / logical for you though? :-)

**Comment by onionhammer** [comment]
Yep, looks great

**Comment by isaacabraham** [comment]
@onionhammer could you check out the branch and try it out?

**Comment by onionhammer** [comment]
@isaacabraham Cloned it and tested your sample script; works perfectly fine
