### ISSUE TITLE
Examples for implementation of unsupported ARM resources

### ISSUE THREAD

**Issue by Skovvart** [CompositionalIT/farmer#315]
https://compositionalit.github.io/farmer/faq/#can-i-add-resources-that-are-not-supported-by-farmer states that unsupported resources can be implemented in a variety of ways (.NET object adapters, embedding ARM JSON directly), but I have been unable to find any examples anywhere in the documentation of how to implement either.
Perhaps it is super simple, but as someone new to Farmer, this seems like a killer feature that is not super intuitive and would be worth documenting.

**Comment by isaacabraham** [comment]
Hi @Skovvart. Have a look at the [Contributing](https://compositionalit.github.io/farmer/contributing/adding-resources/) section of the docs - this has a step-by-step guide on building up resources from raw JSON all the way through to a full Builder. It's written in a guide / recipe style - perhaps we should also create a more reference docs style section.

**Comment by isaacabraham** [comment]
Let me know if that section is enough for you or if you need anything more.

**Comment by Skovvart** [comment]
Hi @isaacabraham, the updated docs and examples seem to be what I was looking for, at least. Thanks for the update.
