### ISSUE TITLE
Redis generates wrong properties.sku.name value

### ISSUE THREAD

**Issue by fraxu** [CompositionalIT/farmer#317]
Hi,
Redis cache resource is currently broken:

`let redis = redis {
    name "test"
    sku Basic
}`

Generates following invalid json 

`...

"sku": {
          "capacity": 1,
          "family": "C",
          "name": "{ Capacity = 1\n  Sku = Basic }"
}
...`

In cache.fs we should have 

> string this.Sku.Sku

 vs current 

> string this.Sku

I can create PR for this if needed.

**Comment by isaacabraham** [comment]
Please do. I can push out a release once it's in.
