### ISSUE TITLE
disable_kafka doesn't work for EventHubs

### ISSUE THREAD

**Issue by forki** [CompositionalIT/farmer#323]
I tried to use `disable_kafka` but it doesn't set this to the EventHubs namespace.

**Comment by isaacabraham** [comment]
How do you mean, "it doesn't set this to the eventhubs namespace"? The JSON seems to be correctly emitted:

```fsharp
let myEh = eventHub {
    namespace_name "allmyevents"
    disable_kafka
}
```

and

```json
    {
      "apiVersion": "2017-04-01",
      "location": "northeurope",
      "properties": {
        "kafkaEnabled": false
      }
```

**Comment by isaacabraham** [comment]
See the official docs here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.eventhub.models.ehnamespace.kafkaenabled?view=azure-dotnet

**Comment by isaacabraham** [comment]
@forki Looking at some other docs (https://docs.microsoft.com/en-us/azure/templates/microsoft.eventhub/namespaces) and SO posts (https://stackoverflow.com/questions/51539199/azure-event-hub-enable-kafka-in-arm-template) I *think* the issue might be that the value may need to be set as a string, not a "raw" boolean!

I'll test this out.

**Comment by isaacabraham** [comment]
@forki I'm stuck. I don't know what needs to be set to disable Kafka - I've tried all combinations of false, "false", "False" on 2017 and a secret 2018 preview API. Nothing works.

**Comment by isaacabraham** [comment]
Hey @alex-frankel . Any ideas on who I can reach out to on this one? I've tried every combination I can think of but nothing works. We may as well remove the flag if it's doing nothing :-)

**Comment by alex-frankel** [comment]
Just started a thread with the eventhub team and included you on it Issaac. Hopefully we can get it resolved quickly (or at least get an answer as to what is happening)

**Comment by isaacabraham** [comment]
@alex-frankel thanks for helping. We now have determined that this field does nothing and will be deprecated. Therefore we will remove it from Farmer, probably from v1.1 (even though this is a breaking change) as the keyword is misleading and should be removed.
