### ISSUE TITLE
CosmosDb causes JSON serialization error

### ISSUE THREAD

**Issue by BrianVallelunga** [CompositionalIT/farmer#328]
I'm getting an error when adding a Cosmos DB and trying to generate an ARM template. The error is:

> Unhandled exception. Newtonsoft.Json.JsonSerializationException: A member with the name 'tags' already exists on '<>f__AnonymousType4233066337`8[System.String,System.String,System.String,System.String,System.Object,<>f__AnonymousType3068273139`2[System.String,System.String],Microsoft.FSharp.Collections.FSharpMap`2[System.String,System.String],System.String]'. Use the JsonPropertyAttribute to specify another name.

This code will reproduce the issue:

```
let cosmos = cosmosDb {
    name "fred"
}

let deployment = arm {
    location Location.EastUS2
    add_resource cosmos
}

deployment
|> Writer.quickWrite "template"
```

**Comment by isaacabraham** [comment]
Good spot - have added a unit test for this (we should probably add a basic serialization test for all builders) and fixed. Will go out with RC2.

**Comment by isaacabraham** [comment]
@BrianVallelunga released in rc2 just now.

**Comment by BrianVallelunga** [comment]
I just verified this works now, thanks!
