### ISSUE TITLE
User-assigned managed identities?

### ISSUE THREAD

**Issue by BrianVallelunga** [CompositionalIT/farmer#330]
I don't see this supported yet, but I'm wondering what it would take to support user-assigned managed identities on a web app. Right now there's a single enable_managed_identity option. Is it limiting to have that be a simple "enable" toggle? Or perhaps it could be expanded in the future to include a parameter of a ManagedIdentity list of some sort.

Now that I have time and a project to use with Farmer, I'd love to contribute some new resources.

**Comment by isaacabraham** [comment]
@BrianVallelunga the managed identity was a basic implementation - as you say, you may want to add more than just the system identity. I'm not sure how it works in ARM to be honest - I only did enough to get it up and running for standard KeyVault use cases.

When wouldn't the standard system identity be enough?

**Comment by BrianVallelunga** [comment]
I'm starting to move our system to managed identities and the problem with system identities is that when you have a number of app/sites and they each need access to a bunch of resources you end up with a huge cross product of access policies that need to be created. So if we have 10 function apps that each need access to a common Service Bus, Key Vault, and Database that ends up being 30 access policies that need to be created. It's much easier to create a single managed identity that each service can use.

It would be one thing if you could easily add the system identities to a group and then give the group access, but that's not possible, as far as I know.

**Comment by isaacabraham** [comment]
@BrianVallelunga would you expect to see here the ability to assign an existing managed identity that you've already made? e.g.

```fsharp
webApp {
   enable_managed_identity 123123123
}
```

where 123123123 is the principal id of the identity that you've created?

**Comment by BrianVallelunga** [comment]
Yes, but it should be an array of identities. The ARM code it generates actually creates key/value objects per identity and sets the type to "UserAssigned". Here's a sample with one identity:

```json
"identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
        "/subscriptions/SUBSCRIPTION_ID/resourcegroups/RESOURCE_GROUP_NAME/providers/Microsoft.ManagedIdentity/userAssignedIdentities/IDENTITY_NAME": {
            "principalId": "PRINCIPAL_ID",
            "clientId": "CLIENT_ID"
        }
    }
}
```

**Comment by isaacabraham** [comment]
@BrianVallelunga You'll be pleased to know that this is now ready to be merged in. Feel free to review the PR (#394).

**Comment by BrianVallelunga** [comment]
This looks great. Thanks! I'm officially using Farmer in a new project now and it's working quite well.
