### ISSUE TITLE
Functions link_to_service_plan confusion/bug?

### ISSUE THREAD

**Issue by BrianVallelunga** [CompositionalIT/farmer#332]
Using the `webApp` builder I can call `link_to_service_plan` and pass in my `ServicePlanConfig` object, but for the `functions` builder, there's only a single option to pass in a name, which seems to be of type `ExternalKind`.

I have three questions:
1. Does the functions version have a bug?
2. If it doesn't, what exactly do I reference if I already have a ServicePlanConfig.
3. Can the functions builder have all of the overloads that the webApp has?

Here's the `webApp` lines of code: https://github.com/CompositionalIT/farmer/blob/e2bc98adbaabfbaa56c0354f6aca87b41a6ae828/src/Farmer/Builders/Builders.WebApp.fs#L326-L329

And here's the `functions` code: https://github.com/CompositionalIT/farmer/blob/e2bc98adbaabfbaa56c0354f6aca87b41a6ae828/src/Farmer/Builders/Builders.Functions.fs#L175-L176

Thanks!

**Comment by isaacabraham** [comment]
Yes, WebApps and Functions are different enough that we created two separate builders, so there are some differences. Adding this in is appreciated - thank you for doing ti.
