### ISSUE TITLE
CosmosDB - add support for new "serverless" option

### ISSUE THREAD

**Issue by JordanMarr** [CompositionalIT/farmer#333]
I may do this one...

**Comment by BrianVallelunga** [comment]
I was looking for this as well. It seems like the only difference is in the "capabilities" section of the template, and that several other options would then become not applicable.

**Comment by isaacabraham** [comment]
It's still in preview, but if there's some docs for this, it sounds like a good one to do.

**Comment by JordanMarr** [comment]
Here are the major differences I see in the three resource types:

- Microsoft.DocumentDB/databaseAccounts
  - apiVersion: changes from "2020-03-01" to "2020-06-01-preview"
  - properties:consistencyPolicy:defaultConsistencyLevel changes from "Eventual" to "Session"
  - quite a few other properties are included, but i'm not sure if these are required or defaulted.
- Microsoft.DocumentDB/databaseAccounts/sqlDatabases
  - apiVersion: changes from "2020-03-01" to "2020-06-01-preview"
  - properties:options should not have any shared "throughput" settings
- Microsoft.DocumentDb/databaseAccounts/sqlDatabases/containers
  - apiVersion: changes from "2020-03-01" to "2020-06-01-preview"

I wish I had some documentation on which fields are required, but my gut says that these are the bare minimum changes required.

**Comment by JordanMarr** [comment]
I just noticed that my `add_unique_key` change is not in the Cosmos DB documentation for some reason. :(

**Comment by JordanMarr** [comment]
As I work through implementing this, I have started down the path of simply adding a `serverless` operation.
However, it is only valid to configure the `cosmosDb` with _either_ a specified `throughput` _or_ `serverless` mode, which doesn't use throughput at all.  

So the way I'm doing it now is good because adding a new field is not a breaking change, and (FWIW) it aligns closely with the json template; however, it does open the possibility for users to create an invalid configuration that contains both (or neither).  
This may be acceptable though, since the onus is on the users to understand what they are configuring.

Ex:
```
let cosmosDb = cosmosDb {
    name "foo-dev"
    // throughput 400<CosmosDb.RU> // should not exist if serverless is enabled
    serverless
    add_containers []
}
```

But I do wonder if it would be better to combine `throughtput` and `serverless` operations into a new one:
`model` which would take a DU: 
```
type CosmosDbAccountModel = 
| SharedThroughput of int<CosmosDb.RU>
| Serverless
```

It might look like this:
```
let cosmosDb = cosmosDb {
    name "foo-dev"
    model (SharedThroughput 400<CosmosDb.RU>)
    add_containers []
}
```

or

```
let cosmosDb = cosmosDb {
    name "foo-dev"
    model Serverless
    add_containers []
}
```

This would help to prevent invalid states, but it would be a breaking change.

Unless anyone has an opinion, I guess I will continue going down the simple path of adding a `serverless` field.


One last thing to consider is that there is another model that is not currently supported in the Farmer cosmosDb builder which is throughput specified at the container level.  It can either be specified at the shared level (as it is currently implemented in Farmer), or for each container (for higher traffic scenarios).  See issue #337.

**Comment by JordanMarr** [comment]
I did some more reading and found out this useful tidbit (that I completely missed on my first read) from the [Cosmos DB serverless docs](https://docs.microsoft.com/en-us/azure/cosmos-db/serverless):

**"During the preview release, the only supported way to create a new serverless account is by using the Azure portal."**

So it looks like we'll have to keep this change on ice until the serverless feature goes live.
The good news is that Farmer will have support for the serverless feature as soon as it goes live!  😎

**Comment by isaacabraham** [comment]
Doh :-) Thank you for doing this - let's add it once serverless is available :-)

**Comment by BrianVallelunga** [comment]
Serverless is now GA: https://devblogs.microsoft.com/cosmosdb/build-2021-apps-at-any-scale/

**Comment by JordanMarr** [comment]
Awesome! I'll have to dig out my changes from ages ago; hopefully the merge won't be too bad.

**Comment by JordanMarr** [comment]
I dusted off my changes but they still don't work. 
The latest apiVersion listed on [this page](https://docs.microsoft.com/en-us/azure/templates/microsoft.documentdb/allversions) is only 2021-04-15, so that my have something to do with it. 

¯\_(ツ)_/¯

**Comment by JordanMarr** [comment]
FYI, this is what my generated resource looks like:

```json
        {
            "apiVersion": "2021-04-15",
            "kind": "GlobalDocumentDB",
            "location": "westeurope",
            "name": "foo-account",
            "properties": {
                "capabilities": [{
                        "name": "EnableServerless"
                    }
                ],
                "consistencyPolicy": {
                    "defaultConsistencyLevel": "Eventual"
                },
                "databaseAccountOfferType": "Standard",
                "enableFreeTier": false,
                "publicNetworkAccess": "Enabled"
            },
            "tags": {},
            "type": "Microsoft.DocumentDb/databaseAccounts"
        }
```

My guess is that the latest apiVersion is "2021-04-15" which is still before the Build announcement.

**Comment by dnperfors** [comment]
We have been playing around with an ARM template and minimized it to a working version:

```
    let cosmosDb =
        $"""{{
            "apiVersion": "2020-04-01",
            "kind": "GlobalDocumentDB",
            "location": "westeurope",
            "name": "foo-account",
            "properties": {{
                "capabilities": [
                    {{
                        "name": "EnableServerless"
                    }}
                ],
                "databaseAccountOfferType": "Standard",
                "enableFreeTier": false,
                "locations": [
                    {{
                        "id": "foo-account-westeurope",
                        "failoverPriority": 0,
                        "locationName": "West Europe"
                    }}
                ]
            }},
            "tags": {{ }},
            "type": "Microsoft.DocumentDb/databaseAccounts"
        }}""" |> Resource.ofJson
```

It looks like the missing ingredient is "locations", and it doesn't work with the "2021-04-15" version.

**Comment by JordanMarr** [comment]
I'm not sure how to implement location. Usually the location is set at the arm / resourceGroup level. 
Plus there is also a location id - not sure if that needs to be looked up or not.

**Comment by dnperfors** [comment]
I am just playing with it again, and it looks like you can skip the id and failoverPriority, so only the locationName needs to be set.

The way it is implemented now, the locations are only filled when the failover is used and the location from the arm / resourceGroup is used for the first entry.  It seems strange that this was working, because by looking at the specs, the locations have been required a long time.
My suggestion would be to always specify the `locations` property with the the location that is set in the arm / resourceGroup, even when not using serverless. But serverless doesn't work without it...
