### ISSUE TITLE
Transparent Data Encryption invalid name error

### ISSUE THREAD

**Issue by MNie** [CompositionalIT/farmer#340]
When using a SQL builder to construct a server with a database and with enabled encryption like that:

```fsharp
let sqlServer env = sqlServer {
  name (sprintf "server%sdbserver.database.windows.net" env)
  admin_username (sprintf "sqladmin%s" env)
  enable_azure_firewall

  elastic_pool_sku Sql.PoolSku.Basic50
  add_databases [
    sqlDb {
      name (sprintf "db%s" env)
      sku Sql.DbSku.Basic
      use_encryption
      collation "SQL_Latin1_General_CP1_CI_AS"
    }
  ]
}
```

I got following error in Azure Devops:

```bash
##[error]Deployment template validation failed: 'The template resource 'dbtest/current' for type 'Microsoft.Sql/servers/databases/transparentDataEncryption' at line '1' and column '4242' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-template/#resources for usage details.'.
```

I assume that since generated part of ARM template looks like this:

```javascript
{
    "apiVersion": "2014-04-01-preview",
    "comments": "Transparent Data Encryption",
    "dependsOn": [
      "dbtest"
    ],
    "name": "dbtest/current",
    "properties": {
      "status": "Enabled"
    },
    "type": "Microsoft.Sql/servers/databases/transparentDataEncryption"
},
```

The name for a Transparent Data Encryption should has a single segment, so instead of `dbtest/current` it should be `current`, am I right?

If yes, [here](https://github.com/MNie/farmer/tree/feature/transparent_data_encryption) are the needed changes, I could create a pr with them.

**Comment by isaacabraham** [comment]
Great spot!

I think the issue is that the name needs to actually also contain the *server name* as well as the database name e.g. `server/database/current`. I've done a basic test and that seems to work - if you can supply a PR for this I will happily accept it.

**Comment by MNie** [comment]
@isaacabraham sure, pr created : )
