### ISSUE TITLE
isHnsEnabled couldn't be updated as it is read-only.

### ISSUE THREAD

**Issue by MNie** [CompositionalIT/farmer#346]
After update from 0.19.0 to 1.0.0 I encounter a problem with `isHnsEnabled` on a resource that was created with previous version of a Farmer (I use `create or update resource group` option in ARM Deployment in Azure DevOps).

```fsharp
let auditLog env = storageAccount {
  name (sprintf "storage123%s" env)
  sku Storage.Sku.Standard_LRS 
  add_private_container (sprintf "some_container-%s" env)
  add_blob_container "some_blob"
}
```

Error information:

```bash
At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
2020-09-09T18:46:32.2176027Z ##[error]Details:
2020-09-09T18:46:32.2177505Z ##[error]AccountPropertyCannotBeUpdated: The property 'isHnsEnabled' was specified in the input, but it cannot be updated as it is read-only. For more information, see - https://aka.ms/storageaccountupdate
2020-09-09T18:46:32.2179490Z ##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
2020-09-09T18:46:32.2180868Z ##[error]Task failed while creating or updating the template deployment.
```

I see that this field along with properties for Storage were introduced [here](https://github.com/CompositionalIT/farmer/commit/e18b86af281afc9869bdeb383ef7de55be1cd86e). So the question is, is it acceptable to mark `EnableHierarchicalNamespace` as `bool option` to make it backward compatible or simply following sem ver, while updating from 0.19.0 to 1.0.0 I should also drop and recreate problematic resources?

I try using `enableDataLake`, but the problem still persist.
If the above changes with "optional" `enableHierarchicalNamespace` are acceptable here is a [commit](https://github.com/MNie/farmer/commit/5566c4c955af44aec994531bc86d38acdf5971c4) with a fix (I could provide a pr :) )

**Comment by isaacabraham** [comment]
If I understand correctly, what you're saying is that beforehand, we did not emit the `isHnsEnabled` property but now we do, and even though you never set it before, explicitly setting it as false makes ARM reject the template.

We could make this field optional, and I have no problem pushing this out for either 1.1 or as a patch release. However, we need to be sure that this won't break anyone *since* 1.0! In other words, if you create a new storage account with `isHnsEnabled` as `false`, and then redeploy and miss out the value, will this fail?

**Comment by MNie** [comment]
> If I understand correctly, what you're saying is that beforehand, we did not emit the `isHnsEnabled` property but now we do, and even though you never set it before, explicitly setting it as false makes ARM reject the template.

Correct.

> However, we need to be sure that this won't break anyone since 1.0! In other words, if you create a new storage account with `isHnsEnabled` as false, and then redeploy and miss out the value, will this fail?

Good point, gonna check that and give an update here : )

**Comment by MNie** [comment]
@isaacabraham I created AzureStorage with `isHnsEnabled` set to false and then "update" without `isHnsEnabled` and everything seems to be working just fine.
