### ISSUE TITLE
Azure function from docker container

### ISSUE THREAD

**Issue by MNie** [CompositionalIT/farmer#355]
Is there a way to configure [AzureFunction from a docker container](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image?tabs=bash%2Cportal&pivots=programming-language-csharp)?

CC: @isaacabraham

**Comment by isaacabraham** [comment]
Didn't even know that this was possible :-) Can you deploy this with ARM templates? If not, we could still push this out via the CLI but preference should be ARM wherever possible.
