### ISSUE TITLE
AWS CloudFormation support

### ISSUE THREAD

**Issue by raymens** [CompositionalIT/farmer#357]
I was wondering what your opinion is about adding AWS CloudFormation support.
I have used ARM before but am not that familiar with the templates for CloudFormation, but a quick peek seems to indicate they are roughly similar. Main difference as far as I can see based upon this sample is the split between defining resources and instances.

So I'm mostly wondering if this is a possibility in the future, whenever someone finds the time and need to implement it or if it's a clear no.

```json
{
    "Description" : "Create an EC2 instance running the Amazon Linux 32 bit AMI.",
    "Parameters" : {
        "KeyPair" : {
            "Description" : "The EC2 Key Pair to allow SSH access to the instance",
            "Type" : "String"
        }
    },
    "Resources" : {
        "Ec2Instance" : {
            "Type" : "AWS::EC2::Instance",
            "Properties" : {
                "KeyName" : { "Ref" : "KeyPair" },
                "ImageId" : "ami-3b355a52"
            }
        }
    },
    "Outputs" : {
        "InstanceId" : {
            "Description" : "The InstanceId of the newly created EC2 instance",
            "Value" : {
                "Ref" : "Ec2Instance"
            }
        }
    },
    "AWSTemplateFormatVersion" : "2010-09-09"
}  
```

**Comment by isaacabraham** [comment]
My understanding is that on the AWS side you have [CDK](https://docs.aws.amazon.com/cdk/latest/guide/home.html) for this.

The aim of Farmer is primarily about providing a first-class developer experience for Azure resources, sitting on top of ARM. Theoretically we could emit to whatever we wanted, but I fear that doing this would mean targeting a lowest-common denominator for the abstractions to fit with both Azure and AWS services.

I think the ideas that have been introduced in Farmer could be reproduced to create something very similar for AWS, however.

**Comment by raymens** [comment]
Alright that makes sense to me, thanks!

**Comment by isaacabraham** [comment]
Closing (housekeeping) - if you fancy taking this up as a separate project, let me know - happy to help!
