### ISSUE TITLE
Support for SQL Azure VCore and Serverless

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#359]
Currently we only support DTU model. We should also support VCore and Serverless options.

**Comment by raymens** [comment]
Based upon some template generation I found the following things:

Some additional SKUs need to be added:
- vCore model
 - Tier `GeneralPurpose`
  - `GP_Gen5_x` where `x` is the vCore count between 2 and 80
  - `GP_Fsv2_x` where `x` is the vCore count between 8 and 72 
 - Tier `BusinessCritical`
  - `BC_Gen5_x` where `x` is the vCore count between 2 and 80
 - Tier `Hyperscale`
  - `HS_Gen5_x` where `x` is the vCore count between 2 and 80
- Serverless model
  - `GP_S_Gen5_1` where `x` is the vCore **maximum** count between 1 and 40

For Serverless the following properties are needed:
```
        "minCapacity": {
            "value": "1.75"
        },
        "autoPauseDelay": {
            "value": "60" // minutes
        },
```

For both the following properties are important:
```
   "maxSizeBytes": { // HS has it set to 0
            "value": 1073741824// = 1 GB set using the slider in the Portal
        },
        "tier": {
            "value": "GeneralPurpose" // see other values above
        },
```

Just for vCore (non-serverless):
```
        "zoneRedundant": { // valid for HS
            "value": true
        },
        "licenseType": {
            "value": "BasePrice" // BasePrice = already own a license, LicenseIncluded = pay for license
        },
        "readScaleOut": { // valid for HS
            "value": "Enabled"
        },
        "numberOfReplicas": { // valid for BC and HS, (0-4) for HS and set to 1 for BC
            "value": 1
        },
```

**Comment by isaacabraham** [comment]
@raymens I had a bash at this - please feel free to review the PR and let me know your thoughts.

**Comment by Thorium** [comment]
I think the serverless part, GP_S_Gen5, of the spec was forgotten in the PR.
This is kind of related to #238

```JSON
"sku": {
	"name": "GP_S_Gen5",
	"tier": "GeneralPurpose",
	"family": "Gen5",
	"capacity": 8
},
"properties": {
	"autoPauseDelay": -1,
	"minCapacity": 4,
}
```
