### ISSUE TITLE
Receive storage account key with exisiting ressources

### ISSUE THREAD

**Issue by tforkmann** [CompositionalIT/farmer#365]
Hey there, 

with the latest Farmer version I cannot receive the storage account key if the ressource already exisits.

I try to receive the storage account key like this:

```fs
let outputs =
     deployment
      |> Deploy.tryExecute resourceGroupName []
match outputs with
   | Ok x ->
                match x.TryFind "storage_key" with
                | Some x -> x.ToString()
                | None -> failwithf "Can't find storage Key"
   | Error err -> 
                match err with
                | err when err.Contains "is already in another resource group in this susbscription" -> "resource already exisits"
                |  _ ->
                      failwithf "Error creating infrastructure for %s , exn : %A " resourceGroupName err))
```

I get following error message:

``
Unhandled exception. System.Exception: Error creating infrastructure for dpoctobusprod , exn : "{'additionalProperties': {}, 'code': 'InvalidTemplateDeployment', 'message': "The template deployment 'farmer-deploy-884' is not valid according to the validation procedure. The tracking id is '4442557b-2bed-44cd-9f6d-b4d8473a02ed'. See inner errors for details.", 'target': None, 'details': [{'additionalProperties': {}, 'code': 'PreflightValidationCheckFailed', 'message': 'Preflight validation failed. Please refer to the details for the specific errors.', 'target': None, 'details': [{'additionalProperties': {}, 'code': 'StorageAccountInAnotherResourceGroup', 'message': 'The account dpoctobusprod is already in another resource group in this susbscription.', 'target': 'dpoctobusprod', 'details': None, 'additionalInfo': None}], 'additionalInfo': None}], 'additionalInfo': None}
``

Is there a workaroud for this case?

Thanks in advance!

**Comment by isaacabraham** [comment]
Yes. In this case, you won't want to create a storage account in the account but rather add an output that refers to that existing resource. The code below will do what you need - this is actually already part of the Farmer codebase but not exposed publicly, but in the future we could do that easily enough.

```fsharp
/// Creates a storage account key expression for a given account in a specific resource group.
let buildKey resourceGroup storageAccount =
    let fullyQualified = ArmExpression.resourceId(Arm.Storage.storageAccounts, ResourceName storageAccount, resourceGroup).Value
    sprintf
        "concat('DefaultEndpointsProtocol=https;AccountName=%s;AccountKey=', listKeys(%s, '2017-10-01').keys[0].value)"
            storageAccount
            fullyQualified
    |> ArmExpression.create

let deployment = arm {
    location Location.NorthEurope
    output "storage_key" (buildKey "myResourceGroup" "mystorageaccount")
}
```

**Comment by tforkmann** [comment]
Thanks Isaac!
Tested it today! Works!

Merci!

**Comment by tforkmann** [comment]
When updating to Farmer 1.2. The function buildkey is not working anymore.
How can I fix that?

![image](https://user-images.githubusercontent.com/4168951/100199071-f612de00-2efc-11eb-8fcf-b7dd0b07deaa.png)

**Comment by isaacabraham** [comment]
Can't see the code but I suspect is that either a namespace isn't open or something else along those lines.

We can catch up later this afternoon to discuss?

**Comment by isaacabraham** [comment]
`ArmExpression.resourceId` now replaced with `ResourceId.create`
