### ISSUE TITLE
Time for NuGet package?

### ISSUE THREAD

**Issue by Dzoukr** [CompositionalIT/farmer#37]
Farmer's API seems to be quite stable and personally I don't expect any wild changes now. Maybe we can consider convention  (`add_resource` vs `addResource`), but if you want to keep it that way, maybe it's good time for v1.0.0 release on NuGet?

**Comment by isaacabraham** [comment]
Yeah. I think so. What steps are needed to make this easy to do, ideally as part of devops..

**Comment by isaacabraham** [comment]
I guess next steps are:

1. [ ] Decide on roadmap (Look at #20, #21 and #24 - are these necessary and / or breaking changes?)
2. [ ] Introduce NuGet packaging support.
3. [ ] Tie into the build process with for releases?

**Comment by isaacabraham** [comment]
@Dzoukr I've added the first steps for a nuget package in a branch. Also I've reviewed the package from a "first-time consumer" point of view and have done some (pretty big) changes in terms of namespacing and modules, the idea being that typing `Farmer.` doesn't show a million items but a smaller subset that (hopefully) won't be as intimidating.

**Comment by Dzoukr** [comment]
@isaacabraham Looking at nuget branch right now and looks great. Definitely better to have only subset of resource-related stuff available at one time. :+1: 

If you would need any help, just ping me.

**Comment by isaacabraham** [comment]
Closing :-)
