### ISSUE TITLE
How to read existing configuration

### ISSUE THREAD

**Issue by PawelStadnicki** [CompositionalIT/farmer#370]
I cannot find it in the docs and wonder if it possible to read existing configuration of App Function (for example).
I know that we can check storage key upon Storage Account creation.
But I would like also to use Farmer as a verification tool to check if the resources contains proper configuration on place.

Is that possible?

**Comment by isaacabraham** [comment]
Hmmmm, that's an interesting idea. I think the closest you could get would be to use the what-if functionality - I *believe* that this supports app settings / configuration. So you could supply a template with the correct configuration and run what-if and analyse the results.

Currently we don't give back a proper "object model" for the what-if - we were waiting until it settles down - but now could be a good time to explore this further..

**Comment by isaacabraham** [comment]
Closed in favour of #487
