### ISSUE TITLE
CosmosDB Account name validation

### ISSUE THREAD

**Issue by jfellien** [CompositionalIT/farmer#381]
As I tried to create a CosmosDB Account I entered a wrong name which wasnt catched by name validation like in storage account. I would prefer to have a validation in CosmosDB Account naming too.

This is the message from Azure CosmosDB Acount creation process:
"The name can contain only lowercase letters, numbers and the '-' character, and must be between 3 and 44 characters"

**Comment by isaacabraham** [comment]
I was hoping to put in a more complete naming validation feature for 1.1 but I am pushing that to 1.2, so we can put this in for now.

**Comment by jfellien** [comment]
Sounds reasonable.

Maybe it makes sense to close the issue then?

**Comment by isaacabraham** [comment]
Hmmm. Not really - I'm not planning on implementing all validation rules, but rather putting in a pattern and set of types to do it. We'll then need to implement it across all resources as needed.

**Comment by mymo2202** [comment]
H

**Comment by mymo2202** [comment]
D

**Comment by mymo2202** [comment]
Dependency	[jasmine-node](https://github.com/mhevery/jasmine-node)

**Comment by Firgeis** [comment]
I'm wanting to contribute, just have some questions on the current Validation implementation. Do you prefer questions here or is there a other channels for discussion?

**Comment by isaacabraham** [comment]
Here is good :-)
