### ISSUE TITLE
Add a self Id lookup for keyVault accessPolicy

### ISSUE THREAD

**Issue by JordanMarr** [CompositionalIT/farmer#390]
It would be cool if when creating a access policy if there was an easy way to add yourself without having to manually look up your Id.

So instead of using "object_id", if there was "my_id" or something like that.

For example, instead of this:
```
let adminAccessPolicy = accessPolicy {
    object_id "db1b5729-98c9-4e96-a652-defcc7028849" // jmarr@microdesk.com
    key_permissions KeyVault.Key.All
    secret_permissions KeyVault.Secret.All
    certificate_permissions KeyVault.Certificate.All
}

let functionAppAccessPolicy = accessPolicy {
    object_id functionsApp.SystemIdentity
    secret_permissions [KeyVault.Secret.List; KeyVault.Secret.Get]
}

let keyVault = keyVault {
    name (buildResourceName "kv")
    sku KeyVault.Standard
    add_access_policy adminAccessPolicy
    add_access_policy functionAppAccessPolicy
}
```

... you could do this:
```
let adminAccessPolicy = accessPolicy {
    object_id MyId
    key_permissions KeyVault.Key.All
    secret_permissions KeyVault.Secret.All
    certificate_permissions KeyVault.Certificate.All
}
```

or maybe 
```
let adminAccessPolicy = accessPolicy {
    my_id
    key_permissions KeyVault.Key.All
    secret_permissions KeyVault.Secret.All
    certificate_permissions KeyVault.Certificate.All
}
```

**Comment by isaacabraham** [comment]
There is actually already a wrapper around CLI to retrieve your Principal ID:

```fsharp
let mememe = KeyVault.AccessPolicy.findUsers [ "isaac@compositional-it.com" ] |> Seq.head

AccessPolicy.create mememe.ObjectId
AccessPolicy.create (mememe.ObjectId, Secret.All)
accessPolicy { object_id mememe.ObjectId; secret_permissions [ Secret.Get; Secret.Delete ] }
```

Is this sufficient or do we need something more than that?

**Comment by JordanMarr** [comment]
Now I see you mentioned this in the "Utilities" section of the Key Vault docs. For some reason I completely skipped over that and only looked at the examples.

It does seem that all the builders are very declarative which makes the imperative nature of the utility functions seem a little out of place. They are not as "in line" with the declarative nature of Farmer.  

With that said, they will definitely suffice. 👍
