### ISSUE TITLE
ARM Template Toolkit validation

### ISSUE THREAD

**Issue by pviotti** [CompositionalIT/farmer#392]
Microsoft recently [introduced](https://azure.microsoft.com/en-us/blog/simplifying-declarative-deployments-in-azure/) a tool to validate ARM templates. I haven't looked into it much, but it seems to be a set of PowerShell Core cmdlets that validate ARM templates. It may be useful to be able to invoke them from Farmer as an optional validation step. https://github.com/Azure/arm-ttk

**Comment by isaacabraham** [comment]
Mmmm. Taking a dependency on Powershell as well as the CLI is something I'd prefer not to do, but on the other hand, having more validation is definitely a good thing.

**Comment by isaacabraham** [comment]
Closing in favour of #505
