### ISSUE TITLE
It should be possible to create a container group without a public IP address

### ISSUE THREAD

**Issue by viktorvan** [CompositionalIT/farmer#404]
**Describe the bug**
It should be possible to create a container group without a public IP address.

**To Reproduce**
Do not set any ip address in the containerGroup builder:

```fsharp
let group = containerGroup {
    name "myGroup"
    operating_system Linux
    restart_policy RestartOnFailure
    add_instances [ myContainer ]
}
```

**Actual behavior**

The generated json-template still contains a property for ip-address, with an empty ports list:

```json
        "ipAddress": {
          "ports": [],
          "type": "Public"
        },
```

Trying to deploy this template causes the following ValidationError:

```ini
ValidationError: Deployment failed. Correlation ID: 2f88c005-49b1-4a0e-9731-8d67cdb0244a. {
  "error": {
    "code": "MissingIpAddressPorts",
    "message": "The ports in the 'ipAddress' of container group 'wordcount' cannot be empty."
  }
}
```

**Expected behavior**

If I do not set the IP address in the containerGroup-builder I expect the json-template to not contain the ipAddress property at all. (a template with "ipAddress": null can also be used, but will generate a warning in visual studio code).

**Comment by isaacabraham** [comment]
Ok, this looks like a simple enough fix.
