### ISSUE TITLE
Can't deploy Linux web app

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#41]
The following template generates a Linux ARM template that is invalid:

```fsharp
let template =
    let myWebApp = webApp {
        name "mysuperwebappisaac"
        sku WebApp.Sku.F1
        operating_system Linux
        runtime_stack DotNetCore22
    }

    arm {
        location NorthEurope
        add_resource myWebApp
    }
```

The service host is deployed, but the web app is not, with an error that the LinuxFxVersion is invalid (in the generated template it's `DOTNETCORE|2.2`).

What do you think this is @Dzoukr ?

**Comment by Dzoukr** [comment]
Hi @isaacabraham,

prepare for a good laugh. I tried and failed with the same error. Then I tried to create a same configuration manually and copy some parts to locally generated ARM template. After some desperate guesses, I realized that output for `Microsoft.Web/serverfarms` is slightly different.

Our output:

```
{
  "apiVersion": "2018-02-01",
  "kind": "linux",
  "location": "northeurope",
  "name": "mysuperwebapproman-plan",
  "properties": {
	"name": "mysuperwebapproman-plan",
	"perSiteScaling": false,
	"reserved": false
  },
  "sku": {
	"capacity": 1,
	"name": "F1",
	"size": "0",
	"tier": "Free"
  },
  "type": "Microsoft.Web/serverfarms"
}
```

the portal template (manual clicked resource) output:

```
{
  "apiVersion": "2018-11-01",
  "name": "mysuperwebapproman-plan",
  "type": "Microsoft.Web/serverfarms",
  "location": "northeurope",
  "kind": "linux",
  "tags": null,
  "dependsOn": [],
  "properties": {
	"name": "mysuperwebapproman-plan",
	"workerSize": "0",
	"workerSizeId": "0",
	"numberOfWorkers": "1",
	"reserved": true,
	"hostingEnvironment": ""
  },
  "sku": {
	"Tier": "Free",
	"Name": "F1"
  }
}
```
The second one sort of works - returns bad request but at least creates resource on Azure. I tried to investigate (= change randomly things and pray) and realized, that **deleting** section `resources` from webApp section containing 

```
"resources": [
	{
	  "apiVersion": "2016-08-01",
	  "dependsOn": [
		"mysuperwebapproman"
	  ],
	  "name": "Microsoft.ApplicationInsights.AzureWebSites",
	  "properties": {},
	  "type": "siteextensions"
	}
]
```

will make it 100% work.

So here is the investigation summary:

1. `apiVersion` is now `2018-11-01`
2. Sku properties for `Microsoft.Web/serverfarms`  now with first letter uppercase make it work. Why? Only God and Microsoft know.
3. Having AI site extension in resources array for `Microsoft.Web/sites` will make it fail.
4. And just to make it more fun - everything works when you choose Windows OS.

(╯°□°)╯︵ ┻━┻

**Comment by isaacabraham** [comment]
So sounds like the site extension is not valid for Linux webapps.

**Comment by isaacabraham** [comment]
Interesting observation is that changing api version to 2018-11-01 is "invalid" in terms of e.g. VS Code intellisense (suggests 2018-0201).

**Comment by isaacabraham** [comment]
@Dzoukr also doing those three things don't fix it for me :-( Where did you get that list of linuxfxversions in the first place?

**Comment by isaacabraham** [comment]
In fact the only way i can get it working is by removing the LinuxFxVersion completely

**Comment by Dzoukr** [comment]
I did manual clicking and checking the template output to get list of LinuxFxVersion values.

**Comment by viktorvan** [comment]
I am having the same issue now, did you get any further on this? 
I actually tried creating a webapp for linux in the portal, but even that fails for me. :(

As a workaround I can use Windows OS for now.

**Comment by isaacabraham** [comment]
I'll chase up - I'm trying to get support from MS.

**Comment by isaacabraham** [comment]
@viktorvan @Dzoukr an you both check now? I've made some changes to the template generation which I think are now working. Not yet released but it's in master

**Comment by viktorvan** [comment]
Yes, I can create a linux webApp now. Thanks!
