### ISSUE TITLE
How to add secret with string literal?

### ISSUE THREAD

**Issue by BrianVallelunga** [CompositionalIT/farmer#416]
Is there an easy way to add a KeyVault secret with a string literal as the value?

I think I can do the following, but it probably makes sense to add an override so that `value` can directly take a string.

``` f#
let mySecret = secret {
    name "MySecret"
    value ("MySecretValue" |> ArmExpression.literal)
}
```
My use case is that we put our environment name in KeyVault and while it's technically not a secret, it makes sense to store it there with our other configuration.

My ideal code would look like:

``` f#
let environment = "Dev" // Passed in from args actually
let envSecret = secret {
    name "Environment"
    value environment
}
```

**Comment by isaacabraham** [comment]
@BrianVallelunga Hey. So I really wanted to avoid allowing plain text secrets to be entered directly into key vault - this is kind of a security hole because it lets people do "the wrong thing" (notwithstanding the fact that you are using KV as a kind of setting store rather than secret store here).

However, if you are literally just doing basic key / value pairs of secrets, you can use the `add_secret` overload:

```fsharp
let v = keyVault {
    name "test"
    add_secret "environment"
}
```

This will create a Secure Parameter that you pass in when running the template:

```fsharp
template
|> Deploy.execute "my-resource-group-name" [ "environment", "Dev" ]
```

This is more geared up towards providing security (because "Dev" will never show up in the ARM template) but should also work for you?

**Comment by BrianVallelunga** [comment]
Most of our KeyVault secrets are connection strings, API keys, etc, but we have found it beneficial to store other settings there as well because it centralizes configuration. There's some gray area as well. For example, should the endpoint for Cosmos be considered a secret? The key certainly is, but storing the endpoint separate from the key just makes the overall configuration too confusing. We use Azure.Extensions.AspNetCore.Configuration.Secrets to bring our config into all of our apps and functions and it works well.

I'll take a look at using secret parameters for this functionality, though we're not deploying with Farmer, we're using Octopus Deploy's Azure ARM template step for that right now.

Not to go on too much of a tangent, but it turns out Azure offers an entire App Configuration feature separate from KeyVault that does almost the same thing, but with a slightly different feature set. See here, if you have never heard of it (https://azure.microsoft.com/en-us/services/app-configuration/). I wish they had just integrated KeyVault's functionality into that product. It would make life easier to have a single store of information.

**Comment by isaacabraham** [comment]
Yep, there's an issue to add that into Farmer too. I believe that that service *does* actually provide some kind of implicit pass-through into KeyVault somehow, so although you'll need two services, you at least can just refer to one.

You can still use Farmer with Octopus's ARM template step:

1. Generate the ARM template from within Farmer - it will create a template with the secure parameters as needed.
2. Set up Octopus to take that generated template.
3. I imagine Octopus's ARM template feature has support for parameters - set them up in Octopus to make the parameter names that Farmer created.
4. Profit :-)

**Comment by isaacabraham** [comment]
Closing this. I think the real outcome is to add support for Azure's Configuration service, and I believe there's already an issue for that.
