### ISSUE TITLE
Add PremiumV3 skus for web apps

### ISSUE THREAD

**Issue by stevebelskie** [CompositionalIT/farmer#434]
PremiumV3 skus were added for app service plans were added recently. 

Adding support for these at basic level looks as though it may be as simple as adding another case to WebApp Sku in Common.fs

```fs
type Sku =
        | Shared
        | Free
        | Basic of string
        | Standard of string
        | Premium of string
        | PremiumV2 of string
        | PremiumV3 of string
        | Isolated of string
        | Dynamic
```

And then adding the appropriate members

```fs
 static member P1V3 = PremiumV3 "P1V3"
 static member P2V3 = PremiumV3 "P2V3"
 static member P3V3 = PremiumV3 "P3V3"
```

Still poking around and familiarizing myself with the code, so I may be missing something more that would need to be changed.

 I'd be happy to submit a pr for this change.

**Comment by isaacabraham** [comment]
@stevebelskie Probably that's all that's required. On that Sku type we also have some members for common SKUs by their "common names" so it may be worth adding those as well e.g. B1, S2 etc.
