### ISSUE TITLE
Allow adding tags to resource group

### ISSUE THREAD

**Issue by ssiltanen** [CompositionalIT/farmer#457]
If I am not mistaken, it is not possible to create resource groups other than in deployment where only resource group name is specified. Should deploy function also accept a ResourceGroup item (this would need a new builder too), which could hold tags and possibly other values?

**Comment by isaacabraham** [comment]
I think that this should just be a keyword directly on the `arm { }` builder e.g.

```fsharp
let template = arm {
    add_resource x
    add_resource y
    add_tags [ "test"; "generated-with-farmer"; "bar" ]
}
```

**Comment by ssiltanen** [comment]
That would make it much simpler, although is it ambiguous which resource is being tagged? Also shouldn't they be tuples for key-value?

**Comment by isaacabraham** [comment]
@ssiltanen i thought the tags are being set at the resource group level itself? in which case this is the logical place to put it.

Yes, probably right re: tuple.

**Comment by TheRSP** [comment]
Is it possible to close this issue now? I believe it is now possible to add tags to resource groups.

**Comment by isaacabraham** [comment]
Always happy to close off an issue. I'm good at doing that!
