### ISSUE TITLE
Azure CLI commands assume output is json

### ISSUE THREAD

**Issue by NatElkins** [CompositionalIT/farmer#461]
I found this while looking into https://github.com/SAFE-Stack/SAFE-template/issues/411 .  Basically, some parts of farmer assume that the output will be JSON, as on this line: https://github.com/CompositionalIT/farmer/blob/a98e8b43f686d4c7c14e325c8a8faf80b4d7bcbf/src/Farmer/Deploy.fs#L214

In my case, my default output is set to `table`.

I haven't looked too closely but it may be worth it to change the function actually starting the `az` process to add `-o json` to the end of every command (somewhere [here ](https://github.com/CompositionalIT/farmer/blob/a98e8b43f686d4c7c14e325c8a8faf80b4d7bcbf/src/Farmer/Deploy.fs#L44-L69) I think).

**Comment by isaacabraham** [comment]
Good idea.
