### ISSUE TITLE
FunctionsConfig not respecting ResourceRef/ExternalKind

### ISSUE THREAD

**Issue by TheRSP** [CompositionalIT/farmer#467]
We have the following type extension to the functions builder:

```fs
type FunctionsBuilder with
    [<CustomOperation("link_to_unmanaged_storage_account")>]
    member this.LinkToUnmanagedStorage (state:Farmer.Builders.Functions.FunctionsConfig, storageAccountId) =
       {state with StorageAccount =  External ( Unmanaged ( storageAccountId )) }
```

However, owing to the way `FunctionsConfig` sets the dependencies, the external-ness of this is ignored:

```
member this.StorageAccountName : Storage.StorageAccountName = this.StorageAccount.resourceId(this).Name |> Storage.StorageAccountName.Create |> Result.get
// ...
              Dependencies = Set [
                yield! this.Dependencies
                match this.AppInsights with
                | Some (DependableResource this resourceId) -> resourceId
                | _ -> ()
                for setting in this.Settings do
                    match setting.Value with
                    | ExpressionSetting e -> yield! Option.toList e.Owner
                    | ParameterSetting _ | LiteralSetting _ -> ()
                match this.ServicePlan with
                | DependableResource this resourceId -> resourceId
                | _ -> ()

                storageAccounts.resourceId this.StorageAccountName.ResourceName
              ]
```

Is it possible to
1. Respect the external-ness of ResourceRef
2. Add unmanaged operator overloads to the Functions Builder to give parity with the WebApp builder?

**Comment by isaacabraham** [comment]
I'm surprised that we do it on WebApps to be honest, but yes there should be parity between them in terms of extensions.

The thinking behind not doing this was simply that you shouldn't ever "need" to depend on an external resource since the resource must already exist if you're referring to it by name in your Farmer template.

What's the use case you're thinking of here?

**Comment by isaacabraham** [comment]
Or are you rather saying that we *should* be checking and that we currently aren't?

**Comment by TheRSP** [comment]
Yeah I believe it should only be including the StorageAccount in the dependencies if it is _not_ External. However the current code unconditionally adds the storage account to the dependencies and therefore there is no way to make the FunctionsApp work with a non-farmer-controlled storage account.

**Comment by TheRSP** [comment]
Our use case is that we have a single shared storage account which we use for all of our company functions but the functions belong to different parts of the system and are therefore in different resource groups.

**Comment by isaacabraham** [comment]
Yeah, that's a bug, this should respect the External nature.

I think if you were to create the resourceId by also supplying the resource group name (this is an optional parameter on the `resourceId` function) the template *should* work for now.

**Comment by isaacabraham** [comment]
Fixing that now. Putting in the fully qualified path won't help you either as we drop off everything but the name currently.

**Comment by isaacabraham** [comment]
@TheRSP this will be pushed out as part of the next 1.3 release. Just note: don't have two azure functions instances that share the same storage account as the dashboard (or maybe even the leases) probably won't work. That's why have isolated storage accounts for each functions instance is IMHO better practice.

**Comment by TheRSP** [comment]
Thank you for the fix. I've passed on your warnings about sharing storage accounts to my colleagues working with the functions I think we'll be adjusting our plans based on this. Thank you.
