### ISSUE TITLE
Add 64-bit worker support

### ISSUE THREAD

**Issue by KieranChandler** [CompositionalIT/farmer#468]
Would it be possible to add support for changing the worker process to 64-bit on the webapp builder please?

**Comment by isaacabraham** [comment]
Yes, it would. Could you send the ARM template code that is needed for this, we can then look to schedule that in? Ta.

**Comment by KieranChandler** [comment]
Sure, so the property is called "use32BitWorkerProcess" and is under the "properties" property of "Microsoft.Web/sites/config"

Below is an example config entity in ARM with the property being set to false, causing the worker process to be created as a 64-bit worker process:
`{
      "name": "[concat(variables('WebAppName'), '/web')]",
      "type": "Microsoft.Web/sites/config",
      "apiVersion": "2019-08-01",
      "location": "UK South",
      "dependsOn": [
        "[resourceId('Microsoft.Web/sites', variables('WebAppName'))]"
      ],
      "properties": {
        "numberOfWorkers": 1,
        "defaultDocuments": [],
        "remoteDebuggingVersion": "VS2019",
        "publishingUsername": "[concat('$', variables('WebAppName'))]",
        "use32BitWorkerProcess": false,
        "alwaysOn": true,
        "managedPipelineMode": "Integrated",
        "virtualApplications": [
          {
            "virtualPath": "/",
            "physicalPath": "site\\wwwroot",
            "preloadEnabled": true
          },
          {
            "virtualPath": "/Webjobs",
            "physicalPath": "site\\jobs",
            "preloadEnabled": false
          }
        ],
        "loadBalancing": "LeastRequests",
        "experiments": {
          "rampUpRules": []
        },
        "autoHealEnabled": false,
        "localMySqlEnabled": false,
        "managedServiceIdentityId": 1971,
        "ipSecurityRestrictions": [
          {
            "ipAddress": "Any",
            "action": "Allow",
            "priority": 1,
            "name": "Allow all",
            "description": "Allow all access"
          }
        ],
        "scmIpSecurityRestrictions": [
          {
            "ipAddress": "Any",
            "action": "Allow",
            "priority": 1,
            "name": "Allow all",
            "description": "Allow all access"
          }
        ],
        "scmIpSecurityRestrictionsUseMain": false,
        "http20Enabled": true,
        "minTlsVersion": "1.2",
        "ftpsState": "AllAllowed",
        "preWarmedInstanceCount": 0
      }
    }`

**Comment by isaacabraham** [comment]
@KieranChandler are there any other rules around 32/64 bit e.g. if 64 bit set then something else must be a certain value?

**Comment by isaacabraham** [comment]
So, if anyone wants to pick this up, you'll need to add `"use32BitWorkerProcess": false,` to the output of the web app ARM template and cascade that up to the builder as a new keyword e.g. `use_32bit_worker_process true` or `worker_process 32Bit` (and create an DU for 32Bit | 64Bit).
