### ISSUE TITLE
Farmer shouldn't silently rename MS SQL Server name

### ISSUE THREAD

**Issue by ronnieholm** [CompositionalIT/farmer#477]
I noticed that Farmer allows the name of MS SQL Server to be specified as "foo-bar", but then silently removes the dash and creates the server as "foobar". It means the Farmer script and Azure portal get slightly out of sync. Instead of the silent rename, perhaps show a warning or error message.

**Comment by isaacabraham** [comment]
Yes, this should be fixed as the behaviour nowadays is to fail fast.
