### ISSUE TITLE
Add Support for Databricks Workspaces

### ISSUE THREAD

**Issue by cmarshall10450** [CompositionalIT/farmer#480]
It would be nice to be able to deploy Databricks workspaces using both the managed network and Bring Your Own Vnet model. Databricks workspaces are a core component of all the ARM templates that I work on. 

Has this been requested and denied previously? Are there any known limitations to implementing this support?

I'd be happy to work on this feature. It would be my first contribution to an OSS project.

**Comment by isaacabraham** [comment]
@cmarshall10450 hey. Nope, there's no reason why it's not in here except that no-one has requested it yet :-) There's a basic guide to creating new resources on the docs site in the contributing section - it's a little out of date (apologies) but should be good enough to get you going - happy to answer any questions you might have as you go through it.

The hardest part I suspect you'll have is working out the ARM template settings for it, but some resources are simpler than others.

**Comment by cmarshall10450** [comment]
@isaacabraham Hey, thanks for the quick reply and offer of help. It may take me a bit longer to implement than usual and I may ask some stupid questions. This will also be my first time writing any F# but hopefully it'll all go ok. I'd also like to add support for Data Factories but I'll raise that in a separate ticket.

**Comment by cmarshall10450** [comment]
@isaacabraham Is there an existing method to retrieve the resource id of a resource group by name?

**Comment by isaacabraham** [comment]
Hmmm, resource groups aren't resources insofar as they don't have an id. What are you trying to do?

Data Factory - that'd be awesome. I think for that (like some others e.g. Logic Apps) we'll have to separate create the "resource" itself and the "metadata" about the factory (the data pipelines etc.).

**Comment by cmarshall10450** [comment]
I didn't think they'd be counted as resources. There is a property on the workspace resource called "managedResourceGroupId" which is for which resource group should be created for all internal resources such as VMs, NICs and public IPs but it needs to be given as the full resource id. I've added it as an ArmExpression, which should work OK.

Yeah, for now I was thinking of only imprlemtning the data factory resource. The metadata parts are a much larger undertaking that I may take on after the resources are done.

**Comment by cmarshall10450** [comment]
@isaacabraham Do you know how I can map an Option to a record but return null if the Option is a None? I need to convert the properties into a structure with a "value" key but not include the property at all if the value is not set. 

```fsharp
{| customVirtualNetworkId = 
        this.ByovConfig |> Option.map (fun config -> {|value = config.Vnet|}) |> Option.toNullable
   customPublicSubnetName = 
        this.ByovConfig |> Option.map (fun config -> {|value = config.PublicSubnet|}) |> Option.toNullable
   customPrivsteSubnetName =
        this.ByovConfig |> Option.map (fun config -> {|value = config.PrivateSubnet|}) |> Option.toNullable
|}
```

This gives an error that the record doesn't have a public constructor. It also happens if I create a Property type. The value also needs to be able to handle different data types e.g a string or another type. 

This is probably the wrong way to go about it but I can't find a better way to do it as leaving the values as Option types doesn't give the right output in the template.

**Comment by isaacabraham** [comment]
@cmarshall10450 I've added some comments as a review - thanks for this :-)

**Comment by isaacabraham** [comment]
For that case, you have two options: either use box, as you have done, or create return a Map / Dictionary of the key / value pairs - JSON .NET will correctly hydrate them into the JSON as fields.
