### ISSUE TITLE
Make Writer.quickDeploy cross-platform

### ISSUE THREAD

**Issue by viktorvan** [CompositionalIT/farmer#50]
Is anyone working on making Writer.quickDeploy cross-platform?

I have written something that at least works on my mac, so that would at least be one more platform 🙂 but I think it _should_ work on linux as well. I can make a pull-request from that to get a discussion going. Maybe you have some more requirements for this function that my solution doesn't support.

**Comment by isaacabraham** [comment]
Excellent, I was thinking to add such an issue. I have no clue how to do that, so yes, definitely worth getting the discussion going.
