### ISSUE TITLE
App Insight Instrumentation Key for Linux Web App

### ISSUE THREAD

**Issue by Szer** [CompositionalIT/farmer#509]
Why Farmer doesn't fill in Instrumentation Key for Linux WebApps?

https://github.com/CompositionalIT/farmer/blob/ae6289d7a33457045f564ac6cee5647bed0b7806/src/Farmer/Builders/Builders.WebApp.fs#L188-L201

**Comment by isaacabraham** [comment]
Because Linux Web Apps don't support AI integration.

But thinking about it now, we should probably always push out the instrumentation key, just not all the other settings, right?

**Comment by Szer** [comment]
Yep, Instrumentation Key is the only thing needed for it to work
