### ISSUE TITLE
Add Functions Support for Elastic Premium ServerFarm SKU

### ISSUE THREAD

**Issue by tehmufifnman** [CompositionalIT/farmer#512]
(also note the new property field maximumElasticWorkerCount)
Same ARM JSON:
```
    {
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2020-06-01",
      "name": "[parameters('appName')]",
      "location": "[resourceGroup().location]",
      "tags": "[parameters('resourceTags')]",
      "kind": "elastic",
      "sku": {
        "name": "EP1",
        "tier": "ElasticPremium"
      },
      "properties": {
        "maximumElasticWorkerCount": 20,
        "targetWorkerCount": 0,
        "targetWorkerSizeId": 0
      }
    },

**Comment by tehmufifnman** [comment]
For Context:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan#available-instance-skus

**Comment by isaacabraham** [comment]
Ok, this is a functions thing (rather than webapps)?

**Comment by tehmufifnman** [comment]
> Ok, this is a functions thing (rather than webapps)?

Correct - sorry should have been more specific in my initial post!

**Comment by isaacabraham** [comment]
Related to #498 - I think that the always on flag will be necessary to deal with only after setting this (although I suspect that even then it will be possible to leave it blank and have azure default it for us).
