### ISSUE TITLE
BUG: Cosmos container creates invalid resourceId reference in 1.3

### ISSUE THREAD

**Issue by BrianVallelunga** [CompositionalIT/farmer#513]
I just upgraded to 1.3 and I've found a bug while creating a Cosmos collection. This is my code:

```f#
let cosmos = cosmosDb {
    name cosmosDatabaseName
    account_name cosmosAccountName
    throughput 400<CosmosDb.RU>
    failover_policy CosmosDb.NoFailover
    add_containers [
        cosmosContainer {
            name "mycontainer"
            partition_key ["/id"] CosmosDb.Hash
        }
    ]
}
````

The output ARM template contains the following for the "mycontainer" container:
```json
"dependsOn": [
     "[resourceId('Microsoft.DocumentDb/databaseAccounts/sqlDatabases', 'DatabaseName')]"
]
```

This does not validate and fails deployment. From looking at an exported template, I believe the correct call to `resourceId` should contain the account name parameter as well:
```json
"dependsOn": [
     "[resourceId('Microsoft.DocumentDb/databaseAccounts/sqlDatabases', 'AccountName', 'DatabaseName')]"
]
```

**Comment by isaacabraham** [comment]
Thanks - good spot. This is indeed a bug introduced by the new way we're generating resource paths - it was a big change, hence why we left 1.3 in beta for so long to hopefully iron out any broken changes.

We've also added an automated regression test for many resources' ARM output; I'll add Cosmos to this as well and we'll push out a patch ASAP.

**Comment by isaacabraham** [comment]
I'm surprised that this doesn't also fail validation on the database itself, because that follows the same pattern i.e. the type of resource (sqlDatabases) and then the DB name - no account name is provided either.

**Comment by BrianVallelunga** [comment]
Thanks. I moved back to 1.2 for the moment, but will try everything out once the patch is out.

**Comment by isaacabraham** [comment]
@BrianVallelunga 1.3.1 has just been released with a fix

**Comment by isaacabraham** [comment]
I also identified another issue whereby we were setting the incorrect type for the database account and fixed that at the same time.

**Comment by BrianVallelunga** [comment]
Great, I'm testing it now.

**Comment by isaacabraham** [comment]
Fixed by [this commit](https://github.com/CompositionalIT/farmer/commit/28c8ac22abfc4a27bde2a0077d97a777df61b156).

**Comment by BrianVallelunga** [comment]
Works for me! Thanks for the fix.
