### ISSUE TITLE
Using SecureParameters when running quickDeploy

### ISSUE THREAD

**Issue by viktorvan** [CompositionalIT/farmer#52]
A question, when trying to deploy a sql-server by running the quickDeploy-command I get an error that the password parameter is missing:

> Please provide securestring value for 'password-for-v-test-sql' 

When deploying the generated arm-template manually I can provide the parameter, of course, so in a production scenario it works fine.

But what is a good way to do this when using quickDeploy?

I actually interpreted the following section in the readme to mean that a (development) password would be automatically generated, but maybe I misunderstood:

> Farmer does support securestring parameters for e.g. SQL and Virtual Machine passwords - these are automatically generated based on the contents of the template rather than explicitly by yourself. However, we don't currently plan on providing rich support for either parameters or variables for several reasons:

So is there a workaround for this that I am not seeing, or can I not use quickDeploy for resources that require SecureParameters?

**Comment by isaacabraham** [comment]
The wording is obviously a little misleading :-) Farmer will automatically generate the *parameters* themselves for you, but not the values.

Perhaps the quick deploy option should do that. But how?

* As arguments to quick deploy itself e.g.

```fsharp
template |> quickDeploy [ "password-for-v-test-sql", "myStupidPassword" ]
```

* Generate them randomly and emit them out to the console?
* Some other way?

**Comment by viktorvan** [comment]
Yes something like that would work I think. But maybe there should be a `quickDeployWithParams` for that?

On the other hand, yes, maybe it is possible to generate the parameters using the hash of the template as a seed or something like that. I mean, it would be very convenient to get an azure development environment up and running by just doing:

```fsharp
template |> quickDeploy
```

And by that getting some random SecureStrings generated as passwords.

**Comment by isaacabraham** [comment]
Ok, I've created a basic routine that can create a parameter file. At the moment the password is crude - just a Guid - but that can be changed in time. It also needs wiring into the quick deploy process. Have a look at the auto-generate-password branch!

**Comment by viktorvan** [comment]
Looks good, but I had an issue. I just had time for a quick try, though. It seems it works fine when setting the password, for example in my sql-server. However when I tried to reference the password in a functions app:

```fsharp
let myFunctions = functions {
    name "v-test-funcs"
    depends_on mySqlDb
    setting "dbPassword" mySqlDb.AdministratorCredentials.Password.AsArmRef
}
```

It does not resolve to the password from the parameter file, just "[parameters('password-for-v-test-sql')]". I haven't had a chance to look at the source code, maybe it's something obvious I am missing.

**Comment by isaacabraham** [comment]
Hmmm, can you raise a separate issue for that?

**Comment by viktorvan** [comment]
Sorry, I was a bit wrong here, the snippet above actually works. It’s when I try to interpolate a string that it is not escaped properly. 

I wanted to do something like
```fsharp
let connString = sprintf “connection string stuff... Password=%s” mySqlDb.AdministratorCredentials.Password.AsArmRef

let myFunctions = functions {
    name "v-test-funcs"
    depends_on mySqlDb
    setting "connectionString" connString
}
```

Should this be possible? In that case I can open another issue, otherwise the workaround of just using 
```fsharp
setting “dbPassword” mySqlDb.AdministratorCredentials.Password.AsArmRef
```
works for me.

**Comment by isaacabraham** [comment]
Basically we need to emit a string that uses 'concat' in the ARM expression dialect: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-array#concat

@viktorvan what we might need to do is resurrect the Arm Expression builder I had in an earlier version of Farmer - this gave you strongly typed access to a mini-dsl around ARM's string concatination functions, which we need here. I dropped it after we stopped supporting parameters and variables but as we're now supporting secure parameters, we'll probably need them again.

As as quick test, can you try this out:

```fsharp
let passwordRef = sprintf "[concat('connection string stuff ...', %s, '...')]" (database.AdministratorCredentials.Password.AsArmRef.Trim [| '['; ']' |])

let fns = functions {
    name "isaacsfunctions"
    setting "sqlpass" passwordRef
    depends_on database.ServerName
}
```

And see if it works?
