### ISSUE TITLE
link to unmanaged service plan for Builders.Functions

### ISSUE THREAD

**Issue by Iamabdul** [CompositionalIT/farmer#524]
In some cases, we would want to create a function app that is linked to a service plan which already exists. This functionality already exists for web apps (if I'm not mistaken, in the form of "link_to_unmanaged_service_plan"). We would essentially want to have the same custom operation copied over to the functions builder.

**Comment by isaacabraham** [comment]
Thanks for this @Iamabdul!

Are there any restrictions on this e.g. can you connect a functions instance to *any* app service plan e.g. B1, S1 etc. or are there any restrictions on this?

If not, I am tempted to simply rationalise the webapp / function stuff a little more - there's an experimental branch where I've used a combination of interfaces and extension methods to essentially "share" keywords across multiple builders. So there is now a common set of keywords for Web App and Functions - and this includes all the service plan ones inside Web App.

**Comment by Iamabdul** [comment]
Hello @isaacabraham ,no worries at all, my bad on the confusion in the other thread lol

I can confirm that I am able to connect the functions instances to the service plans I tested which were B1, S1 and P2V2. I also didn't see any complaints from the farmer templates as the server farm looks qualified for each test, from my end I can't think of any possible restrictions. As a result, would it be safe to assume it can be linked to any service plan?

Regarding the func and webapp similarities, sounds good to me, would the sharing of keywords through the use of interfaces (for both func and webApp) likely result in a breaking change for an update, Or would we be able to keep the settings as is (the using statements staying the same etc - "open")? Also, roughly when do you think we'd be able to get this update?

Thanks again!

**Comment by isaacabraham** [comment]
Exactly, the keywords would be shared across both the Web App and Functions builders through the use of an interface that both builders implement. This shouldn't be a breaking change - I've tested out locally and no code changes were required for any of the unit tests.

From a static typing point of view, nothing will change. If you're doing something funky e.g. reflecting over the builder types, then this would be a runtime breaking change, but one that you would immediately see on running your Farmer template.

**Comment by isaacabraham** [comment]
The code is ready to go I think, it just needs another review and then would be pushed out as part of 1.4 b1 later this week.

**Comment by Iamabdul** [comment]
Great news, thanks for that!

**Comment by isaacabraham** [comment]
@Iamabdul this is now 1.4b1, you can test this out at your convenience.
