### ISSUE TITLE
Remove BingSearch from Cognitive Services.

### ISSUE THREAD

**Issue by MNie** [CompositionalIT/farmer#526]
[BingSearch API would be moved out from the Cognitive Services](https://azure.microsoft.com/en-us/updates/bing-search-apis-will-transition-from-azure-cognitive-services-to-azure-marketplace-on-31-october-2023/). We could align this change in the #440.

CC: @isaacabraham?

**Comment by isaacabraham** [comment]
Mmmm. I think we should just remove these from cognitive services. If and when it's offered via ARM from the marketplace, we can add it back in then.
