### ISSUE TITLE
SqlServer PasswordParameter is removing non-letter characters

### ISSUE THREAD

**Issue by aorlenko83** [CompositionalIT/farmer#549]
I'm using sqlServer builder. As per documentation, it adds the ARM secured parameter with following format: `password-for-{server_name}` . The issue is that if I provide string containing non-letter characters as server name, the actual PasswordParameter appears to be letters-only. 
For example, the "my-test-server" name is transformed to "mytestserver".
This causes the following code not working
`Deploy.execute "my-resource-group" [ transactionalDb.PasswordParameter, "SQL PASSWORD GOES HERE" ]`
because in ARM we have "my-test-server", whereas in program runtime PasswordParameter="mytestserver".

**Comment by isaacabraham** [comment]
Looks like a bug. We used to do a lot of "silent" renaming in case a string was invalid for a service but have moved away from that to just fail fast. This looks like it was missed.

**Comment by isaacabraham** [comment]
Can you retest this using 1.4.0 (either beta1 or beta2, which was released today) - I've testing this locally and dashes etc. are there. We did recently rework how the SQL password validation worked (per my comment above) and it's possible you're on an older version that had this issue.

**Comment by aorlenko83** [comment]
1.4.2-beta2 works, thanks.
