### ISSUE TITLE
Deterministic Guid Algorithm Incorrect

### ISSUE THREAD

**Issue by dunnry** [CompositionalIT/farmer#552]
The algorithm for deterministic guid might be slightly incorrect.  As such, it is incompatible with deterministic guids created with other libraries (e.g. [here](https://github.com/Faithlife/FaithlifeUtility/blob/master/src/Faithlife.Utility/GuidUtility.cs)).

The issue seems to be that the namespace guid is not byte swapped to network order.  [See implementation here](https://github.com/Faithlife/FaithlifeUtility/blob/master/src/Faithlife.Utility/GuidUtility.cs#L94).

If update the algorithm to include the swap bytes on the namespace guid, it makes identical guids and becomes compatible.  I made the change locally and tested it to prove this does fix it.

The fix is to simply call `swapBytes` at [this line](https://github.com/CompositionalIT/farmer/blob/64e415902a8fc883739d9b30383a9cdbf324d532/src/Farmer/Types.fs#L308)

Edit:  I looked up the RFC and indeed, you should be swapping the namespace guid into network order. [See here](https://tools.ietf.org/html/rfc4122#section-4.3).

**Comment by isaacabraham** [comment]
Thanks for pointing this out. Any chance you could submit a PR to fix this? Ta

**Comment by dunnry** [comment]
Sure... will send it along shortly.
