### ISSUE TITLE
Add feature to set current stack to net5 

### ISSUE THREAD

**Issue by tforkmann** [CompositionalIT/farmer#557]
![image](https://user-images.githubusercontent.com/4168951/107626050-8390df00-6c5d-11eb-82a6-80966c55a3a1.png)

It would be great if Farmer can set the current stack on a web app.

Thank you in advance!

**Comment by isaacabraham** [comment]
Could you include the export of the ARM template here as well?

**Comment by tforkmann** [comment]
[ExportedTemplate-dpoctobusprod.zip](https://github.com/CompositionalIT/farmer/files/5970246/ExportedTemplate-dpoctobusprod.zip)

I guess the template should include this:
![image](https://user-images.githubusercontent.com/4168951/107741409-6287c700-6d0d-11eb-9669-082ca907fc47.png)

**Comment by isaacabraham** [comment]
Interestingly I'm not sure what happens if you don't set this. I've deployed a net5 app and it seems to work without setting this.
