### ISSUE TITLE
Make it easier to use secure parameters in the context of an ARM expression

### ISSUE THREAD

**Issue by isaacabraham** [CompositionalIT/farmer#56]
Linked to #52. Now that we support secure parameters, we need to be able to easily e.g. splice them together using things like ARM's `concat`.

**Comment by isaacabraham** [comment]
@viktorvan Can you check out the expression-concat branch and try this:

```fsharp
let database = sql { } // create db here...

// either using raw sprintf
let passwordRef = sprintf "concat('connection string stuff ...', %s, '...')" database.AdministratorCredentials.Password.AsArmRef.Value |> ArmExpression

// or using a custom function that knows how to splice values together correctly.
let passwordRef = ArmExpression.concat [ literal "connection string stuff ..."; database.AdministratorCredentials.Password.AsArmRef; literal "..." ]

let fns = functions {
    name "isaacsfunctions"
    setting "sqlpass" passwordRef // just use here...
    depends_on database.ServerName
}
```

**Comment by viktorvan** [comment]
I’ll try that when I am at my computer, but in the mean time I had another crazy idea 😁

Both the alternatives above force the user to know that you have to “concat” arm parameter values. What if, instead, the setting-function hides this away by checking if the value is an ArmRef, i.e. if it contains any substrings “[parameters(‘<key>’)]”. They can then be replaced with the “concat” syntax required by the arm-template schema?

**Comment by viktorvan** [comment]
Ok, I had a chance to try the `concat` function and it worked fine, but I ended up with this:

```fsharp
let connectionString = 
    concat 
        [ sprintf 
              "Server=tcp:%s.database.windows.net,1433;Initial Catalog=%s;Persist Security Info=False;User ID=%s;Password="
              mySqlDb.ServerName.Value
              mySqlDb.DbName.Value
              mySqlDb.AdministratorCredentials.UserName
          |> literal
          mySqlDb.AdministratorCredentials.Password.AsArmRef
          literal ";MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" ]
```

Which I don't think looks very nice though. Like I commented above, it would be nice to have some way to hide the `concat` away.

I'll sleep on it, and think some more.

**Comment by isaacabraham** [comment]
We can build a helper method on sql db to create a connection string?

**Comment by viktorvan** [comment]
Yes, that’s a great solution, much simpler 👍

**Comment by isaacabraham** [comment]
Try now :-)

**Comment by viktorvan** [comment]
Yes that works for me. Nicely done. :)
