### ISSUE TITLE
External AI and App Service Plan for Function app

### ISSUE THREAD

**Issue by alexanderbikk** [CompositionalIT/farmer#560]
I'm trying to create the Function app with external resources. I can do it using external Storage Account but I can't provide the references for AI and App Service Plan. I got syntax error.

I'm using the latest version of the Farmer library and FSharp.Core 5.0.1
What I'm doing wrong?

Here is my code 

    open Farmer
    open Farmer.Builders
    
    let rgName = "test-salesforce"
    let storageAccountName = "testsfstorageacc"
    let aiName = "test-sf"
    let servicePlanName = "test-sf-function"   
      
    let servicePlanLink = ResourceId.create(Arm.Web.serverFarms , ResourceName servicePlanName, rgName)
    let storageAccountLink = ResourceId.create(Arm.Storage.storageAccounts , ResourceName storageAccountName, rgName)
    let aiLink = ResourceId.create(Arm.Insights.components, ResourceName aiName, rgName)       
    
    let functions = functions {
        name "test-sf-function"  
        link_to_unmanaged_storage_account storageAccountLink
        //link_to_unmanaged_app_insights aiLink
        //link_to_unmanaged_service_plan servicePlanLink
    }
    
    let deployment = arm {
        location Location.WestEurope
        add_resource functions  
    }
    
    deployment
    |> Writer.quickWrite "test-sf-function"
    
 And here is an example with AI and Service plan
 
![image](https://user-images.githubusercontent.com/16937972/107972386-6ee57b80-6fbc-11eb-9852-d5e2cdff4ba9.png)

I have checked the [tests ](https://github.com/CompositionalIT/farmer/blob/4329b790ece78a0f1ef28a9aeabcb986e5e93016/src/Tests/Functions.fs#L38)for the function and see that only "link_to_unmanaged_storage_account" used there. I'm not familiar with F# so it's hard to find the related source code. I can see that in [docs ](https://compositionalit.github.io/farmer/api-overview/resources/functions/)these keywords supported

Also I can't see these keywords in InteliSense which I believe means that these keywords aren't available.

**Comment by isaacabraham** [comment]
@alexanderbikk Hey. Those keywords have been introduced as part of 1.4 - currently in beta and available on Nuget. It'll be released in full this week.

We don't have a great way of highlighting in the docs versions for specific keywords I'm afraid :-/

I have tested your code here on 1.4 and it does indeed compile:

![image](https://user-images.githubusercontent.com/1781813/107974402-d26caa80-6fb6-11eb-921c-a3987d7779f8.png)

**Comment by alexanderbikk** [comment]
Hmm I have checked that version 1.4.0-beta2 already available. Just updated and it solved my issue. Looks like the docs refer to the latest version which is in beta. 

Btw, awesome project :)

**Comment by alexanderbikk** [comment]
@isaacabraham Thank you for such quick answer! Already got it :)

Btw I have one question. Probably it's better to ask it in Discussion.

If I want to create the structure when some shared resources exists and should be used in other resources. And I would like to use Farmer to generate and deploy all these resources in one project. So the one file with all resources it's probably not a good idea. 

I probably should have something like modules\libraries(sorry not familiar with F#) per resource and put some parameters there. So each module can be reusable per environment for example. Then I can create  C# console application and managed my deployments there.

Any thoughts on it? :)

**Comment by isaacabraham** [comment]
@alexanderbikk BTW - we are *considering* removing the shared storage account from functions. It's actually somewhat dangerous as you should never share multiple functions instances on a single storage account (as far as I'm aware).

**Comment by isaacabraham** [comment]
And yes, in answer to your main question, yes, that would be the sort of approach I would suggest - creating an F# project (same as C# project) with some organisation of types and parameterise it for environment.

If you need more support, we have a variety of [professional support plans](https://www.compositional-it.com/consultancy/farmer/) here, including one which comes with an hour or consultancy a month to help with challenges such as this.

**Comment by alexanderbikk** [comment]
> @alexanderbikk BTW - we are _considering_ removing the shared storage account from functions. It's actually somewhat dangerous as you should never share multiple functions instances on a single storage account (as far as I'm aware).

I thought about one storage account per environment where only one function resource will be exists. 
You probably talking about one shared storage account for many function apps(not in my case). Hmm not sure about it actually will consider, thanks.

**Comment by alexanderbikk** [comment]
> And yes, in answer to your main question, yes, that would be the sort of approach I would suggest - creating an F# project (same as C# project) with some organisation of types and parameterise it for environment.
> 
> If you need more support, we have a variety of [professional support plans](https://www.compositional-it.com/consultancy/farmer/) here, including one which comes with an hour or consultancy a month to help with challenges such as this.

I got it, thanks :)

**Comment by isaacabraham** [comment]
> I thought about one storage account per environment where only one function resource will be exists.
You probably talking about one shared storage account for many function apps(not in my case). Hmm not sure about it actually will consider, thanks.

@alexanderbikk in which case, consider creating the storage account as part of the Farmer resource (and then don't use "unmanaged" resources) or just let the functions instance create it.

Storage accounts are very, very, very cheap :-)

**Comment by alexanderbikk** [comment]
@isaacabraham it make sense of course :).

But from my point of view the external "unmanaged" storage still can be useful in some cases. It's just an option which we can be used or not. So, nice to have it. But of course it should be used wisely :)
