### ISSUE TITLE
Azure Function missing use_managed_keyvault

### ISSUE THREAD

**Issue by evannielsen** [CompositionalIT/farmer#561]
I was attempting to create and Azure Function and wanted to create settings that were referenced from a KeyVault. In one of the tutorials in the docs it shows this working as part of a web app setup using use_managed_keyvault. This option does not appear to be available for an Azure Function.

Is this an intentional decision? Is there an example of creating Function settings with values from KeyVault?

**Comment by isaacabraham** [comment]
No reason - it just needs to be implemented.

**Comment by isaacabraham** [comment]
In the interim, you can manually construct those settings using the KeyVault reference structure.

**Comment by evannielsen** [comment]
Would you be able to direct me to an example of how this would work?

**Comment by isaacabraham** [comment]
See [here](http://localhost:1313/farmer/tutorials/web-storage-keyvault/) - the bottom of that tutorial shows you the format your setting needs to be in.

The functions instance's SystemIdentity (or another identity that the app is running in) will need to be trusted by KeyVault with permissions to read and list secrets.

**Comment by VitalyBrusentsev** [comment]
@isaacabraham it looks like you've posted a localhost link :) - [this](https://compositionalit.github.io/farmer/tutorials/web-storage-keyvault/) seems to be the correct one.

Incidentally, I cannot find `use_managed_keyvault` anywhere in this repository, except for the mentioned docs, and this issue 😄  
Is it currently located in some alpha feature branch, or do I use GitHub search incorrectly?

**Comment by isaacabraham** [comment]
Doh. Sorry about that @VitalyBrusentsev! And you're right - the docs were out of date. It was renamed (for consistency) to `link_to_keyvault` and `link_to_unmanaged_keyvault` instead. The docs have now been fixed (and a PR ready to add support for Functions).
