### ISSUE TITLE
keyVault{}: add_tags or add_tag results in a compile error

### ISSUE THREAD

**Issue by VitalyBrusentsev** [CompositionalIT/farmer#574]
It seems to be impossible to use `add_tag` or `add_tags` methods in the `keyVault{}` CE.

A minimal example for reproduction:

```fsharp
#r "nuget:Farmer"

open Farmer
open Farmer.Builders

let tags = [
  "a", "b"
  "c", "d"
]

let secretsvault = keyVault {
  name "testvault"
  //add_tags tags
  //add_tag "a" "b"
}
```

Uncommenting lines with `add_tags` or `add_tag` would lead to the following compile errors:
>Error	FS0001	This expression was expected to have type
    'KeyVaultBuilderState'    
but here has type
    'KeyVaultConfig'

and 
>Error	FS0001	This expression was expected to have type
    'KeyVaultConfig'    
but here has type
    'KeyVaultBuilderState'	F# Miscellaneous Files	C:\Projects\F#\Farmer Scripts\KV tags.fsx	12	Active

The same commands work fine in a `webApp` builder, for example.

Assembly version resolved: 
` "Farmer, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null"`

**Comment by isaacabraham** [comment]
Will be fixed in next 1.5.0 beta. Thanks for the report.
