### ISSUE TITLE
Add CORS for Storage Account

### ISSUE THREAD

**Issue by Akash-Mair** [CompositionalIT/farmer#575]
Support for enabling CORS in the storageAccount so that linked webApps are able to connect without the need to go into the azure portal

**Comment by isaacabraham** [comment]
@Akash-Mair could you find a sample ARM template that does this? You can either:

* Look through the officlal [quickstart](https://github.com/Azure/azure-quickstart-templates) samples
* Create a storage account with some CORS settings and then export the ARM template in the portal to see what it generates
* Google - sometimes StackOverflow or a blog will show you how this works with ARM

Once you've found a good sample, copy it in here (and / or link to the sample), as well as (if it exists) the appropriate part of the official Azure ARM template reference docs for it (somewhere under [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2019-06-01/storageaccounts?tabs=json)).

Thanks

**Comment by Akash-Mair** [comment]
Code snippet:
```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "name": "storageAccountName",
      "apiVersion": "2018-02-01",
      "location": "northeurope",
      "kind": "StorageV2",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "tags": {},
      "dependsOn": [],
      "properties": {
        "accessTier": "Hot"
      },
      "resources": [
        {
          "name": "default",
          "type": "blobServices",
          "apiVersion": "2018-11-01",
          "dependsOn": [
            "storageAccountName"
          ],
          "properties": {
            "cors": {
              "corsRules": [
                {
                  "allowedOrigins": [
                    "https://mywebsite.com"
                  ],
                  "allowedMethods": [
                    "GET"
                  ],
                  "maxAgeInSeconds": 0,
                  "exposedHeaders": [
                    "*"
                  ],
                  "allowedHeaders": [
                    "*"
                  ]
                }
              ]
            }
          },
          "resources": []
        },
        {
          "type": "blobServices/containers",
          "apiVersion": "2018-03-01-preview",
          "name": "[concat('default/', 'myFilesToShare')]",
          "dependsOn": [
            "storageAccountName"
          ],
          "properties": {
            "publicAccess": "Blob"
          }
        }
      ]
    }
  ]
}
```


Resources:
- https://stackoverflow.com/questions/41173859/configure-cors-by-using-azure-resource-manager-template/55596476
- https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/2018-07-01/storageaccounts/blobservices?tabs=json
