### ISSUE TITLE
[Documentation issue?] Error adding Farmer if project file is farmer.csproj

### ISSUE THREAD

**Issue by MaxWilson** [CompositionalIT/farmer#595]
I'm not even sure if this is a Farmer issue in the first place or a dotnet CLI issue, but it bit me while doing the Farmer [quickstart](https://compositionalit.github.io/farmer/quickstarts/quickstart-1/). Filing issue in case it can help someone else.

**Repro:**

1.) cd <solution root directory>
2.) mkdir farmer
3.) cd farmer
4.) dotnet new console -lang F#
5.) dotnet add package Farmer

**Expected:** new farmer app

**Actual:** 

```
d:\code\mse\multiTenant\farmer>dotnet add package Farmer
  Determining projects to restore...
  Writing C:\Users\maxw\AppData\Local\Temp\tmpFE34.tmp
info : Adding PackageReference for package 'Farmer' into project 'd:\code\mse\multiTenant\farmer\farmer.fsproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/farmer/index.json
info : Restoring packages for d:\code\mse\multiTenant\farmer\farmer.fsproj...
error: NU1108: Cycle detected.
error:   farmer -> Farmer (>= 1.4.0).
info : Package 'Farmer' is compatible with all the specified frameworks in project 'd:\code\mse\multiTenant\farmer\farmer.fsproj'.
error: Value cannot be null. (Parameter 'path1')
```

**Known workaround:** name the directory for your deployment creation project something other than Farmer.

**Comment by isaacabraham** [comment]
Hey. Thanks for reporting this @MaxWilson - it's actually a NuGet issue that bites people on lots of projects: You can't have a project with the same name as any nuget package. The error message is terribly misleading.
