### ISSUE TITLE
Add runtime-option "dotnet-isolated" for Azure Functions

### ISSUE THREAD

**Issue by viktorvan** [CompositionalIT/farmer#596]
It's now possible to run Azure functions as an [isolated process](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) and use .NET 5.

To get this to work we needed to make the following changes:

Unrelated code is omitted...

```fsharp
//Builders.Functions.fs

type FunctionsRuntime = DotNet_Isolated | DotNet | Node | Java | Python

interface IBuilder with
    member this.BuildResources location = [
        { AppSettings = [
            "FUNCTIONS_WORKER_RUNTIME", (string this.Runtime).ToLower().Replace("_", "-")
          ] } ]
// 
``` 

If it's ok to add this, I'd be happy to add a PR.

**Comment by isaacabraham** [comment]
Hmm perhaps model it as

```fsharp
type RuntimeKind = Isolated | OldFashioned // please pick a better name than this!
type FunctionsRuntime = DotNet of RuntimeKind | Node | Java | Python
```

?

**Comment by isaacabraham** [comment]
But yes in principle adding this would be good.

**Comment by viktorvan** [comment]
Microsoft seems to be calling these alternatives “isolated” / “out-of-process” vs “in-process”. 
E.g. see the roadmap here https://techcommunity.microsoft.com/t5/apps-on-azure/net-on-azure-functions-roadmap/ba-p/2197916

So instead old fashioned we can use “in-process”.
