### ISSUE TITLE
Add ftpsState and ipSecurityRestrictions to WebApp

### ISSUE THREAD

**Issue by viktorvan** [CompositionalIT/farmer#603]
We are using the settings for *ftpsState* and *ipSecurityRestrictions* for our webapps and have had to make custom changes to Farmer for this.

We'd be happy to make a pull-request to add this functionality to the library. Can we push a draft PR and discuss it?

**Comment by isaacabraham** [comment]
Works for me. If you want to put an example of how this would be consumed from an API point of view before investing time in implementing (normally this is the "hardest" part to get right) as a kind of "pre-review" I'd be happy to go help there.

**Comment by viktorvan** [comment]
Everything got in the way of writing this, but I have now finally added a draft PR #748 where we can discuss the proposed API for these features.

My suggestion right now would be something like:
```fsharp
let ip = System.Net.IPAddress.Parse "1.2.3.4"
webapp {
    name "test"
    disable_ftp_service 
    add_allowed_ip_restriction "test-rule" ip
}
```

But we can continue the discussions in the draft PR.
