### ISSUE TITLE
Template doesn't work

### ISSUE THREAD

**Issue by francotiveron** [CompositionalIT/farmer#660]
Simply running the template generated project cause and exception

First run requires different FSharp.Core version

PS C:\Temp\farmer> dotnet new Farmer
The template "Farmer Application" was created successfully.
PS C:\Temp\farmer> dotnet run
C:\Temp\farmer\FarmerApp.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 5.0.0 to 4.7.2. Reference the package directly from the project to select a different version.
C:\Temp\farmer\FarmerApp.fsproj : warning NU1605:  FarmerApp -> Farmer 1.6.2 -> FSharp.Core (>= 5.0.0)
C:\Temp\farmer\FarmerApp.fsproj : warning NU1605:  FarmerApp -> FSharp.Core (>= 4.0.0)
C:\Temp\farmer\FarmerApp.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 5.0.0 to 4.7.2. Reference the package directly from the project to select a different version.
C:\Temp\farmer\FarmerApp.fsproj : warning NU1605:  FarmerApp -> Farmer 1.6.2 -> FSharp.Core (>= 5.0.0)
C:\Temp\farmer\FarmerApp.fsproj : warning NU1605:  FarmerApp -> FSharp.Core (>= 4.0.0)
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'FSharp.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at <StartupCode$FarmerApp>.$Program.main@()

Replacing 4.* with 5.* for FSharp.Core in the project:

PS C:\Temp\farmer> dotnet run
Generating ARM template...Unhandled exception. System.TypeInitializationException: The type initializer for '<StartupCode$Farmer>.$Common' threw an exception.
 ---> System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Text.Encodings.Web, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at <StartupCode$Farmer>.$Common..cctor()

   --- End of inner exception stack trace ---
   at Farmer.Serialization.get_jsonSerializerOptions()
   at Farmer.Writer.toJson@39.Invoke(ArmTemplate x)
   at Farmer.Writer.quickWrite[a](a templateName, IDeploymentSource deployment)
   at <StartupCode$FarmerApp>.$Program.main@() in C:\Temp\farmer\Program.fs:line 15

**Comment by francotiveron** [comment]
Installing System.Text.Encodings.Web 5.0.1 from nuget solves, however the template needs amendment

**Comment by isaacabraham** [comment]
This is a bug with the template, yes. Could you raise an issue in that repo?

**Comment by francotiveron** [comment]
moved to https://github.com/CompositionalIT/farmer-template/issues/7
