### ISSUE TITLE
Deploying in a specific subscription

### ISSUE THREAD

**Issue by francotiveron** [CompositionalIT/farmer#661]
in 
`deployment |> Deploy.execute "email-tracking-rg" Deploy.NoParameters`

How do I specify the subscription where I want the new resource group to be created?

**Comment by francotiveron** [comment]
Solved

Deploy.listSubscriptions
Deploy.setSubscriptions

However an API reference would be handy #662

**Comment by isaacabraham** [comment]
The API will almost certainly be changed in the future to either have a more discoverable API / require a Subscription ID / be part of the resource group deployment itself (as you can now target subscriptions with ARM deployments).
