### ISSUE TITLE
Code works as script but fails as compiled exe

### ISSUE THREAD

**Issue by francotiveron** [CompositionalIT/farmer#669]
The following script 

```
#r "nuget: Farmer"
#r "nuget: System.Text.Json"

open System
open Farmer
open Farmer.Builders

[<Literal>]
let sep = "-"
[<Literal>]
let env = "dev"
[<Literal>]
let baseName = "email-tracking"
[<Literal>]
let resourceGroupSuffix = "rg"
[<Literal>]
let eventHubSuffix = "hub"
[<Literal>]
let eventHubNamespaceSuffix = "hns"
[<Literal>]
let servicePlanSuffix = "asp"
[<Literal>]
let functionAppSuffix = "fun"
[<Literal>]
let keyVaultSuffix = "vlt"

let namePrefix = baseName + sep + env
let resourceGroupName = namePrefix + sep + resourceGroupSuffix
let eventHubName = namePrefix + sep + eventHubSuffix
let eventHubNamespaceName = namePrefix + sep + eventHubNamespaceSuffix
let keyVaultName = namePrefix  + sep + keyVaultSuffix
let keyVaultUri = @$"https://{keyVaultName}.vault.azure.net/"

let resourceName name typ = namePrefix + sep + name + sep + typ

let servicePlanName name = resourceName name servicePlanSuffix
let appName name = resourceName name functionAppSuffix

let servicePlan id = servicePlan {
    name (servicePlanName id)
    sku WebApp.Sku.EP1
    max_elastic_workers 5
}

let app id (servicePlan:ServicePlanConfig) (storage:StorageAccountConfig) deployPath = functions {
    name (appName id)
    link_to_service_plan servicePlan
    link_to_storage_account storage.Name.ResourceName
    system_identity
    //settings [
    //    ("SqlBulkTimeout", "10")
    //    //("VaultUri", vault.Uri.Value.AbsoluteUri)
    //    ("VaultUri", keyVaultUri)
    //    ("EventHubConnectionString", @"Endpoint=sb://email-tracking-*********")
    //]
    //zip_deploy deployPath
}

let eventHub = eventHub {
    name eventHubName
    namespace_name eventHubNamespaceName
    sku EventHub.Standard
    enable_auto_inflate 10
    capacity 5 //TU
    partitions 5 //Partitions can be set only on creation
    message_retention_days 1
}

let receiverStorage = storageAccount {
    name $"rtematrkrecv{env}storage"
}

let processorStorage = storageAccount {
    name $"rtematrkproc{env}storage"
}

let receiverPlan = servicePlan "receiver"
let receiver = app "receiver" receiverPlan receiverStorage  receiverPublishPath
let processorPlan = servicePlan "processor"
let processor = app "processor" processorPlan processorStorage processorPublishPath

let vault = keyVault {
    name keyVaultName
    sku KeyVault.Sku.Standard
    
    add_access_policy (AccessPolicy.create receiver.SystemIdentity)
    add_access_policy (AccessPolicy.create processor.SystemIdentity)
}

let deployment = arm {
    location Location.AustraliaSoutheast    
    add_resources [
        eventHub
        vault
        receiverPlan
        receiverStorage
        receiver
        processorPlan
        processorStorage
        processor
    ]
}

deployment |> Deploy.execute resourceGroupName Deploy.NoParameters

```
succeeds.

However, if I try to make a project with the same code and run it, I get this exception

```
azure-cli                         2.25.0

core                              2.25.0
telemetry                          1.0.6

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\FrancoTiveron\.azure\cliextensions'

Python (Windows) 3.8.9 (tags/v3.8.9:a743f81, Apr  6 2021, 13:22:56) [MSC v.1928 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.

ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: psutil.AccessDenied (pid=39892)
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_common.py", line 447, in wrapper
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 679, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_common.py", line 450, in wrapper
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 766, in exe
PermissionError: [WinError 24] The program issued a command but the command length is incorrect: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 223, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/__init__.py", line 132, in show_version
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in print_styled_text
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 131, in <listcomp>
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/style.py", line 158, in format_styled_text
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1266, in get_parent_proc_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/util.py", line 1254, in _get_parent_proc_name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/__init__.py", line 617, in name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 750, in name
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\psutil/_pswindows.py", line 681, in wrapper
psutil.AccessDenied: psutil.AccessDenied (pid=39892)
To open an issue, please run: 'az feedback'
```

I need to do this as I am tasked to have the farmer code run in azure pipelines, and am tracking the following blob article
http://thecodemanual.pl/2020/12/22/handling-multiple-environment-with-fsharp-farmer

**Comment by isaacabraham** [comment]
Hi Franco.

This appears to be an issue with az cli rather than anything else.

I (or one of our team) would be happy to provide some support and guidance to you through this with one of our [paid support plans](https://www.compositional-it.com/consultancy/farmer/) - let me know if you're interested.

**Comment by francotiveron** [comment]
Hi Isaac, thank you for our answer.
I have recently started a new job with a company called Renewtrak here in Sydney. I am trying to push F# (they are a C# company), and proposed Farmer for IaC. 
If I ask the company to pay for support, they will most likely ask me to not use Farmer. On the other hand, at this stage I don't think it is fair for me to take charge of these expenses for the company.
I'll try something else by myself,
One thing I am trying is to run the script in the pipeline using your Azure DevOps extension.

**Comment by isaacabraham** [comment]
Absolutely agree. I would suggest, like with any tool or service, if a commercial support package for Farmer is saving you time as a developer and providing your organisation value, then it should be reasonable to pay for that.

Obviously, if you or your organisation think that this is not justifying a few hundred pounds a month, then you might want to look at other IaC solutions.

**Comment by francotiveron** [comment]
Hi Isaac.

No luck unfortunately. Trying to run the script fails with the following error

FSharpScript

View raw log

Starting: FSharpScript
==============================================================================
Task         : Execute F# Script
Description  : Executes an F# .fsx script file
Version      : 1.0.0
Author       : Isaac Abraham
Help         : This task executes an arbitrary .fsx file.
==============================================================================
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsi.exe" D:\a\1\s\RMS.EmailTracking\IaC.fsx
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:4892) Warning: Use Cipheriv for counter mode of aes-256-ctr


IaC.fsx(3,1): error FS3216: Package manager key 'nuget' was not registered in [C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools; C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\], []. Currently registered: 



IaC.fsx(3,1): error FS3217: Processing of a script fragment has stopped because an exception has been raised

##[error]The process 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\Tools\fsi.exe' failed with exit code 1
##[error]Exit code 1 returned from process: file name 'C:\agents\2.188.3\externals\node\bin\node.exe', arguments '"D:\a\_tasks\FSharpScript_1ba72b0a-f476-4a91-90a0-b8e7a0cc4337\1.0.0\runFSharpScript.js"'.
Finishing: FSharpScript

**Comment by francotiveron** [comment]
I got it running (not the compiled project but the script version). The following is the yaml pipeline for your reference:

stages:
  - stage: Dev
    jobs:
    - job: IaC
      pool: 
        vmImage: 'windows-latest'
    
      steps:
      - checkout: self
      - task: UseDotNet@2
        displayName: 'use dotnet version'
        inputs:
          packageType: 'sdk'
          version: '5.0.x'
          performMultiLevelLookup: true
          
      - task: NuGetToolInstaller@1
        displayName: 'install nuget'
        inputs:
          checkLatest: true

      - task: AzureCLI@2
        displayName: Azure CLI
        inputs:
          azureSubscription: 'azure-dev'
          scriptType: pscore
          workingDirectory: './RMS.EmailTracking'
          scriptLocation: inlineScript
          inlineScript: dotnet fsi ./IaC.fsx

**Comment by isaacabraham** [comment]
@francotiveron it appears you're running the script directly with FSI. Most people would actually create a full console app instead. I would suggest trying that - good luck.

**Comment by isaacabraham** [comment]
Certainly that devops extension was created long before `#r:"nuget"` existed.

**Comment by francotiveron** [comment]
@isaacabraham Trying to use a console app was my first approach, however I got bit by the issue as described in the initial post of this issue. Hence I didn't have much options than trying with the script. I firstly tried to use your DevOps extension to run F# script, but no luck. So I tried the basic old friend "dotnet fsi" and it worked.
