### ISSUE TITLE
Static web app deployments aren't repeatable.

### ISSUE THREAD

**Issue by fswadling** [CompositionalIT/farmer#673]
Not sure if this is an issue in farmer or in ARM templates themselves, but when I deploy a static web app via farmer, attempts to re deploy fail. I have to delete the static web app, create a new one and delete the github workflow entry for the previous webapp manually.

**Comment by isaacabraham** [comment]
Probably this is something we should loop in the static web app team for - ARM templates should normally be idempotent, so either we're putting something in that we shouldn't, or the behaviour of the template isn't as normal.

Could you supply a reproduction of the issue as a repo?

**Comment by fredswadlingpelt8** [comment]
https://github.com/fswadling/FarmerStaticWebApp.git

Sorry I can't provide a fully working solution to reproduce the issue but nothing seems to be working for me this morning. My farmer script looks like this.

**Comment by fswadling** [comment]
https://github.com/fswadling/FarmerStaticWebApp.git

Sorry I can't provide a fully working solution to reproduce the issue but nothing seems to be working for me this morning. My farmer script looks like this.

**Comment by isaacabraham** [comment]
I'm closing this - tested this week and everything worked.
