### ISSUE TITLE
SampleApp project is broken?

### ISSUE THREAD

**Issue by biltongza** [CompositionalIT/farmer#676]
The SampleApp project doesn't seem to open in Visual Studio (2019, 16.10.3) and ionide-fsharp in vscode also doesn't seem to like it for some reason?

I'm seeing "method not found" in the F# extension log in VSCode:
```
[11:41:54.636 ERR] [LSP Server] HandleClientMessage - Error {"Code": -32601, "Message": "Method not found", "Data": null, "$type": "Error"} when handling notification {"Version": "2.0", "Method": "$/cancelRequest", "Params": {"Value": [[[]]], "$type": "Some"}, "$type": "Notification"}
```

In Visual Studio, the project just appears as a file in the solution and doesn't expand like a usual project does. 

I don't seem to be able to upload screenshots at the moment for some reason, it keeps failing on Github.

Update: I created a blank .NET 5 F# console app, that opens fine... I tried removing the reference to FSharp.Core and the Farmer project and still seeing the issue. I copied the contents of the empty app project file and pasted it into SampleApp.fsproj and still it isn't working? 🤯

**Comment by isaacabraham** [comment]
Try it in VS or Rider, it should work there. Looks like an Ionide issue. cc @baronfel?

**Comment by baronfel** [comment]
That error log is not actually an error, we should probably silence it purely because it causes confusion.

**Comment by baronfel** [comment]
@biltongza did you do a `dotnet restore` of the project prior to opening it in ionide? We currently require that, IIRC.

**Comment by biltongza** [comment]
OK I'm on a completely different machine now and still seeing the same issue.

Yup, restored before opening. Here's vscode:
![image](https://user-images.githubusercontent.com/2845704/124652941-016bb600-de9d-11eb-8bb9-9c0d4c889cc7.png)

Note it says "Not in a F# project (still loading)" at the bottom, and in the ionide panel you can see it's not showing Program.fs under SampleApp.fsproj, and you can't expand the project in that panel.

Same behaviour in VS:
![image](https://user-images.githubusercontent.com/2845704/124653345-7a6b0d80-de9d-11eb-92bf-7d658602fb3d.png)
