### ISSUE TITLE
WebApp/function builders have no support for KeyVaultReferenceIdentity

### ISSUE THREAD

**Issue by TheRSP** [CompositionalIT/farmer#680]
https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#access-vaults-with-a-user-assigned-identity
When using KeyVault references in appsettings/connection strings, you need to explicitly set the identity to use.

**Comment by Ryan-Palmer-CIT** [comment]
I'm not sure if it covers your use case but I have successfully used key vault refs by enabling managed system identity on the app and relevant permissions to the keyvault:
```fsharp
let database = sqlServer {
    name dbServerName
    admin_username dbUsername
    enable_azure_firewall
    add_databases [
        sqlDb {
            sku Sql.DtuSku.S1
            name dbName
        }
    ]
}

let app = webApp {
    name deployName
    setting dbConnStringKey (database.ConnectionString dbName)
    link_to_keyvault (ResourceName vaultName)
    system_identity
}

let vault = keyVault {
    name vaultName
    add_access_policy (AccessPolicy.create(app.SystemIdentity,[KeyVault.Secret.Get]))
}
```

**Comment by Ryan-Palmer-CIT** [comment]
In that example the db connection string will automatically be stored in keyvault and loaded into app settings using a key vault ref.

**Comment by TheRSP** [comment]
We are currently doing something similar however, because we move apps around a bit and often have a few components (eg functions + webapp) we are looking to move towards user assigned identities. By default, the web app will only use the managed identity for key vault references so every time we move an app or add a component, we have to set permissions up. The linked PR allowed using a user-assigned identity for  key vault references.
