### ISSUE TITLE
Making illegal states un-representable at compile time

### ISSUE THREAD

**Issue by Thorium** [CompositionalIT/farmer#693]
Typically when I write F# programs, when they compile they often work.
With Farmer, we are still quite far.

Currently Farmer gathers each builder states and then does its validation at runtime:
[`failwith $"You must specify a username for virtual machine {this.Name.Value}"`](https://github.com/CompositionalIT/farmer/blob/bbc7600ad4039584506b7f4c0152ca59b83213e1/src/Farmer/Builders/Builders.Vm.fs#L72)

Could we go to the direction where the compiler would notice the most clear validation issues?
We still want to keep the current specification freedom and backward compatibility as much as possible.

![illegalstates](https://user-images.githubusercontent.com/229355/125278263-65153980-e30a-11eb-800f-787fa043596a.png)

I think this could be done by splitting the current mega-state of each builder.
Then doing the custom_operators as strongly-typed for only the states that they are allowed.
And if the "final valid state" is not achieved then the compiler will not type-check.

Example:
https://github.com/Thorium/farmer/commit/2881d8b48b13dc394a19870f2b894724622c92db

So in this small code-sample, I have changed the VM-builder as:
- ".Yield" returns type of VmInitialConfig, not a VmConfig.
- "name"-operators are valid for VmInitialConfig and "VmConfig".
- "username" takes an VmInitialConfig and returns VmConfig.

Quite minimal code-change, and now it validates at compile-time, like in the picture.

This is not PR, this is a question of design-decisions, to what direction should Farmer go, to make things more simple for the end-user. For example, things to consider:
- If you have more complex validation rules, how to avoid the explosion of state transformation method count?
- It seems you can't have multiple CustomOperation-attributes in a class for the same name/operation, the overloads have to be listed below each other. That makes the current interface-implementation inherited custom-operators hard. 

I would like to name the VmInitialConfig as
```fsharp
type ``You have to set the username property to make a valid virtual machine`` = ...
```
...then it would be very clear to the user in IDE tooltops. But I know not everyone like the long names.

**Comment by isaacabraham** [comment]
@Thorium I'll have a proper read through of this. In principle I like this idea - I've played around with it although never tried it before like this.

Also though, you can remember that Farmer has a second "compile" stage i.e. generation of the ARM template. So, yes, F# compilation is best, but if we can't get that easily, then compilation at the ARM generation stage is a good place to be, too.

You can do overloads, although they aren't officially supported they do work.(with certain restrictions).

**Comment by Thorium** [comment]
Don't be distracted by the single-case union, it was just a minimal change to share fields between existing state and the new state. It could have been done via changing the states as classes and shared interface, or whatever method. 

The point is having separate types in the transformation methods.

That's the point of computation expression being stronger abstraction than a single monad, it don't have to be only a monoid in a category of endofunctors... or in .NET language, "we don't have to stick with one IMyContext<_>".

**Comment by isaacabraham** [comment]
Yep, I understand - we're already using this technique in the Event Hub builder, I believe, but for a different reason.

**Comment by Thorium** [comment]
Not a blocking issue, will close for now.
