### ISSUE TITLE
CommonWebConfig Composition-over-copying

### ISSUE THREAD

**Issue by TheRSP** [CompositionalIT/farmer#696]
Currently we use a `CommonWebConfig` to represent configuration which is common to WebApps and Functions. To enable this we have methods which copy properties from `WebConfig` and `FunctionsConfig` to `CommonWebConfig` and back.

I was wondering if it might be worth considering using composition here to reduce the overhead involved?
By defining WebAppConfig as follows and a similar change to Functions would allow adding new common properties with less ceremony
```fsharp
{ CommonWebConfig: CommonWebConfig
  HTTPSOnly : bool
  HTTP20Enabled : bool option
  ClientAffinityEnabled : bool option
  WebSocketsEnabled: bool option
  ... }
```

**Comment by isaacabraham** [comment]
Anything that could reduce that ceremony whilst still allowing us to share the data (and, importantly, the custom keywords which are shared across both) would be a win, yes :-)
