### ISSUE TITLE
Adding a certificate to KeyVault

### ISSUE THREAD

**Issue by Thorium** [CompositionalIT/farmer#709]
I have a secret. Let me tell it to you...
Well, it's a certificate really. 

```fsharp
secret {
    name "selfsigned-test"
    content_type "application/x-pem-file"
    enable_secret
    activation_date (DateTime.Today.AddDays -1.)
    expiration_date (DateTime.Today.AddDays 30)
}
```

But where should the content go?
Am I understanding the docs correctly, is this the way to go:

```fsharp
Deploy.execute "myItems" [ "selfsigned-test", """
-----BEGIN PRIVATE KEY-----
MJJE...KDAL
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
MJJE...GIL6
-----END CERTIFICATE-----
"""]
```

...of course, wrong, as it'd still be in the source code... But in theory? I should generate it when I publish and then push it as above?

Related issue: https://github.com/CompositionalIT/farmer/issues/667

**Comment by isaacabraham** [comment]
In Farmer, we explicitly disallowed passing secrets directly in the ARM template - it's the same as e.g. SQL or VM passwords; you need to pass them as parameters when you deploy the template. That *should* also apply here.

**Comment by Thorium** [comment]
Indeed, "selfsigned-test" is now needed parameter, but if I naively try to read the content:
```fsharp
|> Deploy.execute "myItems" [ "selfsigned-test", (System.IO.File.ReadAllText @"C:\Temp\my.pem") ]
```
...then the system crashes for `ERROR: Unable to parse parameter: PRIVATE` where PRIVATE refers to the second word of the pem-file: -----BEGIN **PRIVATE** KEY----- so it's trying to do some string-parsing for the file.

The same happens if I add extra ' marks.

**Comment by Thorium** [comment]
Ok,
I think I'm trying something impossible here.
Importing certificates via ARM is not supported:
https://docs.microsoft.com/en-us/azure/key-vault/certificates/import-cert-faqs#can-i-import-a-certificate-by-using-an-arm-template-

However, I can push them via this:
```
az login
az keyvault certificate import --vault-name MyKeyVault -n selfsigned-test -f c:\temp\my.pem
```
