### ISSUE TITLE
Example of combining Farmer with other tools

### ISSUE THREAD

**Issue by jeckyl2010** [CompositionalIT/farmer#769]
Are there any examples/best-practices on combining Farmer with etc. az cli or PowerShell to configure those detailed elements, which might not be supported by Farmer yet.

Was thinking that Farmer could create all or most services and properties on each of those, and then let PowerShell do the remaining bits.

So PowerShell would kick of Farmer, let it generate the ARM template, deploy it and then script the rest - as I really hate working with ARM natively :)

**Comment by isaacabraham** [comment]
Hi @jeckyl2010 . There's actually a simple Az Cli API wrapper directly in Farmer which lets you call any command and wraps the response in a Result, which can be useful if you need something more.

If you want to use PS as the "controlling" element, that would also be totally fine - you can run your dotnet Farmer app to either deploy the ARM template itself, or just to generate it and then you deploy it from PS using e.g. Azure PS Cmdlets or the AZ Cli.

Lots of options are available for you here :-) Let me know the sorts of things you're thinking of doing.

**Comment by jeckyl2010** [comment]
Hi Isaac.

Sound cool with the AZ CLI API wrapper - do you have a link to an example on how to do this?

**Comment by isaacabraham** [comment]
You can basically just call the `Deploy.Az.az` function e.g.

```fsharp
#r "nuget:Farmer"

open Farmer

let result = Deploy.Az.az "account list" // Ok json of all subs
let failure = Deploy.Az.az "account list fdsfsdf" // Error "az: error: unrecognized arguments: fdsfsdf
```

etc.
