### ISSUE TITLE
Az.loginWithCredentials fails with System.Exception: /usr/bin/env: 'bash': No such file or directory

### ISSUE THREAD

**Issue by ajuch** [CompositionalIT/farmer#800]
I'm having troubles logging into azure with Farmer with the Az.loginWithCredentials function. I'm not sure that this is a Farmer issue because it only appears when using a newer dotnet sdk image:

mcr.microsoft.com/dotnet/sdk:5.0

mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim (a old workaround for https://github.com/NuGet/Announcements/issues/49) works.

How to reproduce:

Work in a fresh dotnet sdk container:
```
docker run --rm -ti mcr.microsoft.com/dotnet/sdk:5.0
```

Install Azure CLI:
```
apt-get update
apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
AZ_REPO=$(lsb_release -cs)
echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list
apt-get update
apt-get install -y azure-cli
```

In fsi try logging into azure:
```
root@327cc73ed366:/# dotnet fsi

Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> #r "nuget: Farmer, 1.6.12";;
[Loading /tmp/nuget/1196--1988b72e-be40-47ae-9a85-f06f9c8c73ff/Project.fsproj.fsx]
namespace FSI_0002.Project

> open Farmer.Deploy;;
> Az.loginWithCredentials "" "" "";;
Binding session to '/root/.nuget/packages/farmer/1.6.12/lib/net5.0/Farmer.dll'...
val it : Result<string,string> =
  Error "/usr/bin/env: 'bash': No such file or directory
"
>
```

**Comment by isaacabraham** [comment]
@ajuch I've just noticed this issue. Is it indeed still an issue - we're running deployments on Linux and haven't noticed this.

**Comment by ajuch** [comment]
@isaacabraham I just re-tested with the current .Net SDK 6.0 docker image, Farmer 1.7.2 and it works now!
