### ISSUE TITLE
Add ConnectionString config for Azure Function Apps

### ISSUE THREAD

**Issue by amine-mejaouel** [CompositionalIT/farmer#873]
Azure Function App supports adding connection strings through the Portal UI.
However, we can't actually do the same with FunctionsBuilder.

I noticed that we already have a connection_string expression in WebAppBuilder, I suggest that we should have the same for FunctionsBuilder.

**Comment by MNie** [comment]
I believe this is resolved by #874?

**Comment by amine-mejaouel** [comment]
Thanks @MNie, yes indeed it is resolved by #874, I'm closing the issue.
