### ISSUE TITLE
SampleApp is netcoreapp3.0?

### ISSUE THREAD

**Issue by BrianVallelunga** [CompositionalIT/farmer#9]
Is there a reason the sample app is 3.0? It seems to compile and run fine as netcoreapp2.2.

**Comment by isaacabraham** [comment]
@BrianVallelunga no. I'm just running netcore3 here and that's the version it generated by default :-) Please feel free to push back to netcore2.2.

**Comment by isaacabraham** [comment]
@BrianVallelunga I've moved back to netcoreapp2.2.
