### ISSUE TITLE
Example of Functions with upload

### ISSUE THREAD

**Issue by PaigeM89** [CompositionalIT/farmer#932]
I'm trying to deploy a Function App with a function, and based on what I understand from the docs, I simply attach a zip file of my compiled function to the function app. However, I don't see my function listed, and I don't get any kind of error output from the deploy.

Could we get expanded docs with a working example of deploying a function inside a Function App?

**Comment by isaacabraham** [comment]
Sure. There is an example of deploying a functions instance [here](https://compositionalit.github.io/farmer/tutorials/serverless-etl/) but it doesn't really cover how to create a functions app. As long as your zip (or just folder - Farmer will zip it up for you) contains a valid Functions app, it should just work.

If you're using F# functions apps, just make sure that you're creating them correctly. This post has (I think) correct guidance on how to do this: https://www.aaron-powell.com/posts/2020-01-13-creating-azure-functions-in-fsharp/.

**Comment by PaigeM89** [comment]
Sorry for the delayed response - I saw the resources for creating the Functions resource, and that works fine, but deploying the functions within it has been giving me problems. Should I be pointing that folder at the source code for the functions or a compiled output directory?

**Comment by isaacabraham** [comment]
@PaigeM89 it should be the compiled output folder.

**Comment by martinbryant** [comment]
Hi @PaigeM89 - can we look to get this issue closed following the suggestion given?
