### ISSUE TITLE
Storage Account - Diagnostic settings

### ISSUE THREAD

**Issue by mike-wade** [CompositionalIT/farmer#971]
Hi team,

I would like to enable diagnostic settings, specifically for Storage Accounts is there a recommended approach for doing this?

Thanks in advance

**Comment by isaacabraham** [comment]
That should already be supported - let me get back to you.

**Comment by teknikal-wizard** [comment]
I just had a quick search and found this example, I think it fits the bill? https://github.com/CompositionalIT/farmer/blob/bf8b9d75a3b5e8b1c411125b14efaf48930e9679/samples/scripts/diagnosticsetting.fsx

**Comment by teknikal-wizard** [comment]
Also here is the dcos page https://compositionalit.github.io/farmer/api-overview/resources/diagnosticsetting/

**Comment by mike-wade** [comment]
That looks like what I need, thanks :). 

I think I had expected to be provisioning the diagnostic settings from the storage account builder rather than a separate builder entirely.
